// js/crafting/fields/construction.js
// Construction Materials Recipes - 70+ recipes for building materials
// Tier 1-7: From Basic Building Blocks to Advanced Structural Materials

export const CONSTRUCTION_RECIPES = {
    
    // ============================================================================
    // TIER 1: BASIC BUILDING MATERIALS (12 recipes)
    // ============================================================================
    
    'Basic Masonry': [
        {
            id: 'stone_block',
            name: 'Stone Block',
            formula: 'Stone + Cutting → Shaped Block',
            ingredients: { Stone: 20, Water: 2 },
            field: 'construction',
            category: 'Basic Masonry',
            tier: 1,
            skillGain: 2,
            target: 100,
            icon: '🪨',
            unlocksAt: 0,
            value: 15,
            description: 'Cut and shaped stone for building foundations.',
            laborMultiplier: 1.1,
            usedIn: ['walls', 'foundations', 'structures']
        },
        {
            id: 'brick',
            name: 'Clay Brick',
            formula: 'Clay + Sand + Firing → Brick',
            ingredients: { Clay: 15, Sand: 5, Fuel: 2 },
            field: 'construction',
            category: 'Basic Masonry',
            tier: 1,
            skillGain: 3,
            target: 100,
            icon: '🧱',
            unlocksAt: 50,
            value: 20,
            description: 'Standard building brick for walls and structures.',
            laborMultiplier: 1.2,
            usedIn: ['walls', 'buildings', 'pavement']
        },
        {
            id: 'cinder_block',
            name: 'Cinder Block',
            formula: 'Cement + Aggregate + Water → Concrete Block',
            ingredients: { Cement: 8, Gravel: 10, Sand: 8, Water: 5 },
            field: 'construction',
            category: 'Basic Masonry',
            tier: 1,
            skillGain: 4,
            target: 100,
            icon: '🧱',
            unlocksAt: 100,
            value: 25,
            description: 'Lightweight concrete block for rapid construction.',
            laborMultiplier: 1.2,
            usedIn: ['walls', 'foundations', 'commercial']
        },
        {
            id: 'adobe_brick',
            name: 'Adobe Brick',
            formula: 'Clay + Sand + Straw → Sun-Dried Brick',
            ingredients: { Clay: 20, Sand: 10, Straw: 5 },
            field: 'construction',
            category: 'Basic Masonry',
            tier: 1,
            skillGain: 2,
            target: 100,
            icon: '🏜️',
            unlocksAt: 25,
            value: 12,
            description: 'Sun-dried mud brick for traditional construction.',
            laborMultiplier: 1.1,
            usedIn: ['desert_buildings', 'traditional', 'earthen_homes']
        }
    ],
    
    'Mortars & Plasters': [
        {
            id: 'lime_mortar',
            name: 'Lime Mortar',
            formula: 'Lime + Sand + Water → Masonry Mortar',
            ingredients: { Lime: 10, Sand: 20, Water: 5 },
            field: 'construction',
            category: 'Mortars & Plasters',
            tier: 1,
            skillGain: 2,
            target: 100,
            icon: '🧪',
            unlocksAt: 0,
            value: 10,
            description: 'Traditional mortar for stone and brick construction.',
            laborMultiplier: 1.1,
            usedIn: ['bricklaying', 'stonework', 'repointing']
        },
        {
            id: 'cement_mortar',
            name: 'Cement Mortar',
            formula: 'Cement + Sand + Water → Strong Mortar',
            ingredients: { Cement: 15, Sand: 25, Water: 8 },
            field: 'construction',
            category: 'Mortars & Plasters',
            tier: 1,
            skillGain: 3,
            target: 100,
            icon: '🧱',
            unlocksAt: 75,
            value: 15,
            description: 'Modern cement-based mortar for structural bonding.',
            laborMultiplier: 1.2,
            usedIn: ['bricklaying', 'blockwork', 'structural']
        },
        {
            id: 'plaster',
            name: 'Plaster',
            formula: 'Gypsum + Lime + Sand → Wall Finish',
            ingredients: { Gypsum: 15, Lime: 5, Sand: 15, Water: 8 },
            field: 'construction',
            category: 'Mortars & Plasters',
            tier: 1,
            skillGain: 3,
            target: 100,
            icon: '🏛️',
            unlocksAt: 60,
            value: 18,
            description: 'Smooth finish for interior walls.',
            laborMultiplier: 1.2,
            usedIn: ['wall_finish', 'ceilings', 'decorative']
        },
        {
            id: 'stucco',
            name: 'Stucco',
            formula: 'Cement + Lime + Sand + Water → Exterior Finish',
            ingredients: { Cement: 12, Lime: 8, Sand: 20, Water: 10 },
            field: 'construction',
            category: 'Mortars & Plasters',
            tier: 1,
            skillGain: 4,
            target: 100,
            icon: '🏠',
            unlocksAt: 120,
            value: 22,
            description: 'Durable exterior wall finish.',
            laborMultiplier: 1.3,
            usedIn: ['exterior_walls', 'facades', 'decorative']
        }
    ],
    
    'Concrete': [
        {
            id: 'concrete_mix',
            name: 'Concrete Mix',
            formula: 'Cement + Aggregate + Sand + Water → Concrete',
            ingredients: { Cement: 15, Gravel: 30, Sand: 20, Water: 10 },
            field: 'construction',
            category: 'Concrete',
            tier: 1,
            skillGain: 4,
            target: 100,
            icon: '🏗️',
            unlocksAt: 150,
            value: 30,
            description: 'Basic concrete for foundations and structures.',
            laborMultiplier: 1.3,
            usedIn: ['foundations', 'slabs', 'columns']
        },
        {
            id: 'reinforced_concrete',
            name: 'Reinforced Concrete',
            formula: 'Concrete + Steel Rebar → Reinforced',
            ingredients: { ConcreteMix: 20, SteelRebar: 5 },
            field: 'construction',
            category: 'Concrete',
            tier: 1,
            skillGain: 6,
            target: 100,
            icon: '🏢',
            unlocksAt: 200,
            value: 50,
            description: 'Concrete with steel reinforcement for structural strength.',
            laborMultiplier: 1.4,
            usedIn: ['beams', 'columns', 'bridges']
        },
        {
            id: 'precast_concrete',
            name: 'Precast Concrete',
            formula: 'Concrete + Molding → Precast Elements',
            ingredients: { ConcreteMix: 25, Mold: 1 },
            field: 'construction',
            category: 'Concrete',
            tier: 1,
            skillGain: 5,
            target: 100,
            icon: '🏭',
            unlocksAt: 180,
            value: 45,
            description: 'Factory-cast concrete elements for rapid assembly.',
            laborMultiplier: 1.3,
            usedIn: ['panels', 'beams', 'pipes']
        }
    ],
    
    // ============================================================================
    // TIER 2: STRUCTURAL MATERIALS (12 recipes)
    // ============================================================================
    
    'Lumber & Timber': [
        {
            id: 'dimensional_lumber',
            name: 'Dimensional Lumber',
            formula: 'Logs → Sawing → Drying → Lumber',
            ingredients: { Wood: 30, Water: 5 },
            field: 'construction',
            category: 'Lumber & Timber',
            tier: 2,
            skillGain: 3,
            target: 200,
            icon: '🪵',
            unlocksAt: 300,
            value: 20,
            description: 'Standard cut lumber for framing.',
            laborMultiplier: 1.2,
            usedIn: ['framing', 'studs', 'joists']
        },
        {
            id: 'plywood',
            name: 'Plywood',
            formula: 'Wood Veneers + Adhesive → Laminated Panels',
            ingredients: { Wood: 25, Adhesive: 3 },
            field: 'construction',
            category: 'Lumber & Timber',
            tier: 2,
            skillGain: 5,
            target: 200,
            icon: '🪚',
            unlocksAt: 350,
            value: 35,
            description: 'Engineered wood panels for sheathing and furniture.',
            laborMultiplier: 1.3,
            usedIn: ['sheathing', 'furniture', 'subfloors']
        },
        {
            id: 'glulam',
            name: 'Glulam (Glue-Laminated Timber)',
            formula: 'Lumber + Structural Adhesive → Laminated Beams',
            ingredients: { DimensionalLumber: 20, StructuralAdhesive: 3 },
            field: 'construction',
            category: 'Lumber & Timber',
            tier: 2,
            skillGain: 7,
            target: 200,
            icon: '🌲',
            unlocksAt: 400,
            value: 60,
            description: 'High-strength engineered wood beams.',
            laborMultiplier: 1.4,
            usedIn: ['beams', 'arches', 'structures']
        },
        {
            id: 'cross_laminated_timber',
            name: 'Cross-Laminated Timber (CLT)',
            formula: 'Lumber + Adhesive → Cross-Laminated Panels',
            ingredients: { DimensionalLumber: 30, StructuralAdhesive: 5 },
            field: 'construction',
            category: 'Lumber & Timber',
            tier: 2,
            skillGain: 9,
            target: 200,
            icon: '🏢',
            unlocksAt: 500,
            value: 80,
            description: 'Massive wood panels for tall timber buildings.',
            laborMultiplier: 1.5,
            usedIn: ['walls', 'floors', 'tall_buildings']
        }
    ],
    
    'Steel Sections': [
        {
            id: 'steel_rebar',
            name: 'Steel Rebar',
            formula: 'Steel + Rolling → Ribbed Reinforcement',
            ingredients: { Steel: 20 },
            field: 'construction',
            category: 'Steel Sections',
            tier: 2,
            skillGain: 4,
            target: 200,
            icon: '⚙️',
            unlocksAt: 450,
            value: 40,
            description: 'Reinforcing steel for concrete construction.',
            laborMultiplier: 1.3,
            usedIn: ['concrete_reinforcement', 'foundations', 'columns']
        },
        {
            id: 'i_beam',
            name: 'I-Beam',
            formula: 'Steel + Hot Rolling → Structural Beam',
            ingredients: { Steel: 35 },
            field: 'construction',
            category: 'Steel Sections',
            tier: 2,
            skillGain: 6,
            target: 200,
            icon: '📐',
            unlocksAt: 550,
            value: 70,
            description: 'Wide-flange steel beam for structural frames.',
            laborMultiplier: 1.4,
            usedIn: ['steel_frames', 'bridges', 'high_rise']
        },
        {
            id: 'steel_column',
            name: 'Steel Column',
            formula: 'Steel + Forming → Hollow Section',
            ingredients: { Steel: 30 },
            field: 'construction',
            category: 'Steel Sections',
            tier: 2,
            skillGain: 5,
            target: 200,
            icon: '🏛️',
            unlocksAt: 500,
            value: 65,
            description: 'Hollow steel section for vertical support.',
            laborMultiplier: 1.3,
            usedIn: ['columns', 'supports', 'structures']
        },
        {
            id: 'steel_truss',
            name: 'Steel Truss',
            formula: 'Steel Sections + Welding → Truss Assembly',
            ingredients: { SteelBeam: 15, Steel: 10, Welding: 2 },
            field: 'construction',
            category: 'Steel Sections',
            tier: 2,
            skillGain: 8,
            target: 200,
            icon: '🏗️',
            unlocksAt: 600,
            value: 90,
            description: 'Triangulated steel framework for roofs and bridges.',
            laborMultiplier: 1.5,
            usedIn: ['roofs', 'bridges', 'towers']
        }
    ],
    
    // ============================================================================
    // TIER 3: INSULATION & ROOFING (10 recipes)
    // ============================================================================
    
    'Insulation': [
        {
            id: 'fiberglass_insulation',
            name: 'Fiberglass Insulation',
            formula: 'Glass Fibers + Binder → Insulation Batts',
            ingredients: { GlassFiber: 20, Binder: 2 },
            field: 'construction',
            category: 'Insulation',
            tier: 3,
            skillGain: 5,
            target: 300,
            icon: '🪫',
            unlocksAt: 800,
            value: 30,
            description: 'Thermal insulation for walls and attics.',
            laborMultiplier: 1.3,
            usedIn: ['wall_insulation', 'attic', 'thermal']
        },
        {
            id: 'mineral_wool',
            name: 'Mineral Wool Insulation',
            formula: 'Basalt + Slag → Spun Fibers',
            ingredients: { Basalt: 15, Slag: 10, Binder: 2 },
            field: 'construction',
            category: 'Insulation',
            tier: 3,
            skillGain: 6,
            target: 300,
            icon: '🧱',
            unlocksAt: 850,
            value: 35,
            description: 'Fire-resistant insulation for high-temperature applications.',
            laborMultiplier: 1.4,
            usedIn: ['fire_stopping', 'acoustic', 'thermal']
        },
        {
            id: 'foam_insulation',
            name: 'Spray Foam Insulation',
            formula: 'Polyurethane + Blowing Agent → Rigid Foam',
            ingredients: { Polyurethane: 15, BlowingAgent: 2 },
            field: 'construction',
            category: 'Insulation',
            tier: 3,
            skillGain: 7,
            target: 300,
            icon: '🫧',
            unlocksAt: 900,
            value: 45,
            description: 'High-R-value insulation for airtight buildings.',
            laborMultiplier: 1.4,
            usedIn: ['air_sealing', 'high_r_value', 'roofs']
        },
        {
            id: 'cellulose_insulation',
            name: 'Cellulose Insulation',
            formula: 'Recycled Paper + Borates → Loose-Fill',
            ingredients: { Paper: 25, Borax: 3 },
            field: 'construction',
            category: 'Insulation',
            tier: 3,
            skillGain: 4,
            target: 300,
            icon: '📄',
            unlocksAt: 780,
            value: 20,
            description: 'Eco-friendly insulation from recycled materials.',
            laborMultiplier: 1.2,
            usedIn: ['green_building', 'retrofit', 'attic']
        }
    ],
    
    'Roofing': [
        {
            id: 'asphalt_shingles',
            name: 'Asphalt Shingles',
            formula: 'Fiberglass Mat + Asphalt + Granules → Roofing',
            ingredients: { Fiberglass: 10, Asphalt: 15, Granules: 8 },
            field: 'construction',
            category: 'Roofing',
            tier: 3,
            skillGain: 5,
            target: 300,
            icon: '🏠',
            unlocksAt: 1000,
            value: 40,
            description: 'Standard residential roofing material.',
            laborMultiplier: 1.3,
            usedIn: ['roofs', 'residential', 'waterproofing']
        },
        {
            id: 'clay_roof_tiles',
            name: 'Clay Roof Tiles',
            formula: 'Clay + Shaping + Firing → Tiles',
            ingredients: { Clay: 30, Glaze: 2 },
            field: 'construction',
            category: 'Roofing',
            tier: 3,
            skillGain: 6,
            target: 300,
            icon: '🏯',
            unlocksAt: 1050,
            value: 50,
            description: 'Durable, attractive clay tiles for pitched roofs.',
            laborMultiplier: 1.4,
            usedIn: ['spanish_style', 'durable_roofs', 'historic']
        },
        {
            id: 'metal_roofing',
            name: 'Metal Roofing Panels',
            formula: 'Steel + Coating → Profiled Sheets',
            ingredients: { Steel: 25, ZincCoating: 2 },
            field: 'construction',
            category: 'Roofing',
            tier: 3,
            skillGain: 6,
            target: 300,
            icon: '🔩',
            unlocksAt: 1100,
            value: 60,
            description: 'Long-lasting metal roofing for commercial buildings.',
            laborMultiplier: 1.4,
            usedIn: ['commercial', 'industrial', 'long_lasting']
        },
        {
            id: 'membrane_roofing',
            name: 'Membrane Roofing',
            formula: 'PVC or TPO + Reinforcement → Single-Ply',
            ingredients: { PVC: 20, PolyesterReinforcement: 5 },
            field: 'construction',
            category: 'Roofing',
            tier: 3,
            skillGain: 7,
            target: 300,
            icon: '🏢',
            unlocksAt: 1150,
            value: 55,
            description: 'Flexible roofing membrane for flat roofs.',
            laborMultiplier: 1.4,
            usedIn: ['flat_roofs', 'commercial', 'waterproofing']
        }
    ],
    
    // ============================================================================
    // TIER 4: FINISHING MATERIALS (10 recipes)
    // ============================================================================
    
    'Flooring': [
        {
            id: 'hardwood_flooring',
            name: 'Hardwood Flooring',
            formula: 'Hardwood + Milling → Finished Planks',
            ingredients: { Hardwood: 30, Finish: 2 },
            field: 'construction',
            category: 'Flooring',
            tier: 4,
            skillGain: 5,
            target: 400,
            icon: '🪵',
            unlocksAt: 1500,
            value: 60,
            description: 'Premium wood flooring for interior spaces.',
            laborMultiplier: 1.4,
            usedIn: ['residential', 'commercial', 'premium']
        },
        {
            id: 'laminate_flooring',
            name: 'Laminate Flooring',
            formula: 'Fiberboard + Print Layer + Wear Layer',
            ingredients: { MDF: 20, PrintLayer: 2, WearLayer: 1 },
            field: 'construction',
            category: 'Flooring',
            tier: 4,
            skillGain: 5,
            target: 400,
            icon: '🏠',
            unlocksAt: 1550,
            value: 35,
            description: 'Affordable flooring with wood appearance.',
            laborMultiplier: 1.3,
            usedIn: ['residential', 'rental', 'budget']
        },
        {
            id: 'vinyl_flooring',
            name: 'Vinyl Flooring',
            formula: 'PVC + Plasticizers → Sheet or Tile',
            ingredients: { PVC: 25, Plasticizers: 3 },
            field: 'construction',
            category: 'Flooring',
            tier: 4,
            skillGain: 4,
            target: 400,
            icon: '🧩',
            unlocksAt: 1600,
            value: 25,
            description: 'Water-resistant flooring for bathrooms and kitchens.',
            laborMultiplier: 1.2,
            usedIn: ['bathrooms', 'kitchens', 'commercial']
        },
        {
            id: 'polished_concrete',
            name: 'Polished Concrete',
            formula: 'Concrete + Grinding + Sealer → Finish',
            ingredients: { ConcreteMix: 30, DiamondGrinding: 1, Sealer: 2 },
            field: 'construction',
            category: 'Flooring',
            tier: 4,
            skillGain: 7,
            target: 400,
            icon: '✨',
            unlocksAt: 1700,
            value: 45,
            description: 'Durable, glossy concrete floor for industrial chic.',
            laborMultiplier: 1.5,
            usedIn: ['warehouse', 'retail', 'modern_homes']
        }
    ],
    
    'Wall Finishes': [
        {
            id: 'drywall',
            name: 'Drywall (Gypsum Board)',
            formula: 'Gypsum + Paper → Wallboard',
            ingredients: { Gypsum: 25, Paper: 5 },
            field: 'construction',
            category: 'Wall Finishes',
            tier: 4,
            skillGain: 4,
            target: 400,
            icon: '🧱',
            unlocksAt: 1400,
            value: 20,
            description: 'Standard interior wall and ceiling panels.',
            laborMultiplier: 1.2,
            usedIn: ['interior_walls', 'ceilings', 'partitions']
        },
        {
            id: 'acoustic_panel',
            name: 'Acoustic Panel',
            formula: 'Fiberglass + Fabric → Sound Absorption',
            ingredients: { FiberglassInsulation: 15, Fabric: 5, Frame: 2 },
            field: 'construction',
            category: 'Wall Finishes',
            tier: 4,
            skillGain: 6,
            target: 400,
            icon: '🔊',
            unlocksAt: 1800,
            value: 50,
            description: 'Sound-absorbing panels for studios and theaters.',
            laborMultiplier: 1.4,
            usedIn: ['recording_studios', 'home_theaters', 'offices']
        },
        {
            id: 'wainscoting',
            name: 'Wainscoting',
            formula: 'Wood Panels + Molding → Wall Treatment',
            ingredients: { Wood: 20, Molding: 5 },
            field: 'construction',
            category: 'Wall Finishes',
            tier: 4,
            skillGain: 6,
            target: 400,
            icon: '🏛️',
            unlocksAt: 1650,
            value: 55,
            description: 'Decorative wood paneling for formal rooms.',
            laborMultiplier: 1.4,
            usedIn: ['dining_rooms', 'hallways', 'traditional']
        }
    ],
    
    // ============================================================================
    // TIER 5: ADVANCED STRUCTURAL SYSTEMS (10 recipes)
    // ============================================================================
    
    'Prefabricated Systems': [
        {
            id: 'prefab_wall_panel',
            name: 'Prefabricated Wall Panel',
            formula: 'Framing + Insulation + Sheathing → Complete Wall',
            ingredients: { DimensionalLumber: 20, Insulation: 15, Plywood: 10 },
            field: 'construction',
            category: 'Prefabricated Systems',
            tier: 5,
            skillGain: 12,
            target: 500,
            icon: '🧱',
            unlocksAt: 2500,
            value: 150,
            description: 'Factory-built wall panel for rapid assembly.',
            laborMultiplier: 1.6,
            usedIn: ['modular_homes', 'rapid_construction', 'efficient']
        },
        {
            id: 'prefab_floor_cassette',
            name: 'Precast Floor Cassette',
            formula: 'Steel Frame + Concrete + Insulation → Floor Module',
            ingredients: { SteelBeam: 10, ConcreteMix: 20, Insulation: 10 },
            field: 'construction',
            category: 'Prefabricated Systems',
            tier: 5,
            skillGain: 14,
            target: 500,
            icon: '🏢',
            unlocksAt: 2700,
            value: 200,
            description: 'Complete floor module with structure and insulation.',
            laborMultiplier: 1.7,
            usedIn: ['multi_story', 'apartments', 'hotels']
        },
        {
            id: 'prefab_bathroom_pod',
            name: 'Prefabricated Bathroom Pod',
            formula: 'FRP Shell + Fixtures + Plumbing → Complete Bathroom',
            ingredients: { FRP: 15, Toilet: 1, Sink: 1, Shower: 1, Plumbing: 5 },
            field: 'construction',
            category: 'Prefabricated Systems',
            tier: 5,
            skillGain: 20,
            target: 500,
            icon: '🚿',
            unlocksAt: 3000,
            value: 500,
            description: 'Fully finished bathroom module ready for installation.',
            laborMultiplier: 2.0,
            usedIn: ['hotels', 'apartments', 'cruise_ships']
        }
    ],
    
    'Structural Composites': [
        {
            id: 'frp_rebar',
            name: 'Fiber-Reinforced Polymer Rebar',
            formula: 'Glass Fibers + Resin → Corrosion-Proof Rebar',
            ingredients: { GlassFiber: 15, EpoxyResin: 10 },
            field: 'construction',
            category: 'Structural Composites',
            tier: 5,
            skillGain: 12,
            target: 500,
            icon: '⚙️',
            unlocksAt: 2800,
            value: 120,
            description: 'Non-corrosive reinforcement for harsh environments.',
            laborMultiplier: 1.6,
            usedIn: ['marine', 'chemical_plants', 'bridges']
        },
        {
            id: 'carbon_fiber_wrap',
            name: 'Carbon Fiber Wrap',
            formula: 'Carbon Fiber + Epoxy → Structural Strengthening',
            ingredients: { CarbonFiber: 15, EpoxyResin: 8 },
            field: 'construction',
            category: 'Structural Composites',
            tier: 5,
            skillGain: 15,
            target: 500,
            icon: '🔄',
            unlocksAt: 3200,
            value: 300,
            description: 'External reinforcement for existing structures.',
            laborMultiplier: 1.8,
            usedIn: ['seismic_retrofit', 'bridge_repair', 'strengthening']
        },
        {
            id: 'frp_structure',
            name: 'FRP Structural Section',
            formula: 'Pultrusion + Fiberglass → Composite Beam',
            ingredients: { GlassFiber: 20, PolyesterResin: 15 },
            field: 'construction',
            category: 'Structural Composites',
            tier: 5,
            skillGain: 14,
            target: 500,
            icon: '📏',
            unlocksAt: 2900,
            value: 180,
            description: 'Lightweight, corrosion-resistant structural member.',
            laborMultiplier: 1.7,
            usedIn: ['chemical_plants', 'water_treatment', 'coastal']
        }
    ],
    
    // ============================================================================
    // TIER 6: SUSTAINABLE & GREEN MATERIALS (8 recipes)
    // ============================================================================
    
    'Green Building': [
        {
            id: 'rammed_earth',
            name: 'Rammed Earth',
            formula: 'Soil + Stabilizer + Compaction → Monolithic Wall',
            ingredients: { Soil: 50, Cement: 5, Water: 10 },
            field: 'construction',
            category: 'Green Building',
            tier: 6,
            skillGain: 10,
            target: 600,
            icon: '🏜️',
            unlocksAt: 4000,
            value: 80,
            description: 'Earthen construction with high thermal mass.',
            laborMultiplier: 1.5,
            usedIn: ['sustainable_homes', 'thermal_mass', 'natural']
        },
        {
            id: 'straw_bale',
            name: 'Straw Bale Construction',
            formula: 'Straw Bales + Plaster → Insulated Wall',
            ingredients: { Straw: 40, LimePlaster: 15 },
            field: 'construction',
            category: 'Green Building',
            tier: 6,
            skillGain: 9,
            target: 600,
            icon: '🌾',
            unlocksAt: 3800,
            value: 60,
            description: 'Highly insulating walls from agricultural waste.',
            laborMultiplier: 1.4,
            usedIn: ['eco_homes', 'insulated_walls', 'natural']
        },
        {
            id: 'hempcrete',
            name: 'Hempcrete',
            formula: 'Hemp Hurd + Lime + Water → Bio-Composite',
            ingredients: { HempHurd: 30, Lime: 15, Water: 10 },
            field: 'construction',
            category: 'Green Building',
            tier: 6,
            skillGain: 11,
            target: 600,
            icon: '🌱',
            unlocksAt: 4200,
            value: 90,
            description: 'Lightweight, insulating, carbon-negative material.',
            laborMultiplier: 1.5,
            usedIn: ['insulation', 'walls', 'carbon_negative']
        },
        {
            id: 'mycelium_brick',
            name: 'Mycelium Brick',
            formula: 'Agricultural Waste + Fungus → Grown Brick',
            ingredients: { Sawdust: 25, MyceliumSpawn: 5 },
            field: 'construction',
            category: 'Green Building',
            tier: 6,
            skillGain: 15,
            target: 600,
            icon: '🍄',
            unlocksAt: 4500,
            value: 120,
            description: 'Biodegradable brick grown from fungus.',
            laborMultiplier: 1.7,
            usedIn: ['compostable', 'temporary', 'experimental']
        }
    ],
    
    'Recycled Materials': [
        {
            id: 'recycled_concrete',
            name: 'Recycled Concrete Aggregate',
            formula: 'Demolition Concrete + Crushing → Aggregate',
            ingredients: { ConcreteWaste: 50 },
            field: 'construction',
            category: 'Recycled Materials',
            tier: 6,
            skillGain: 6,
            target: 600,
            icon: '🔄',
            unlocksAt: 3500,
            value: 20,
            description: 'Crushed concrete for use as aggregate.',
            laborMultiplier: 1.2,
            usedIn: ['base_course', 'drainage', 'new_concrete']
        },
        {
            id: 'recycled_plastic_lumber',
            name: 'Recycled Plastic Lumber',
            formula: 'Mixed Plastics + Extrusion → Lumber Substitute',
            ingredients: { PlasticWaste: 40 },
            field: 'construction',
            category: 'Recycled Materials',
            tier: 6,
            skillGain: 8,
            target: 600,
            icon: '🪵',
            unlocksAt: 3600,
            value: 35,
            description: 'Maintenance-free lumber from recycled plastic.',
            laborMultiplier: 1.3,
            usedIn: ['decking', 'furniture', 'fencing']
        },
        {
            id: 'recycled_steel',
            name: 'Recycled Steel',
            formula: 'Scrap Steel + Electric Arc → New Steel',
            ingredients: { SteelScrap: 40, Energy: 10 },
            field: 'construction',
            category: 'Recycled Materials',
            tier: 6,
            skillGain: 7,
            target: 600,
            icon: '♻️',
            unlocksAt: 3400,
            value: 40,
            description: 'Steel produced from recycled scrap.',
            laborMultiplier: 1.3,
            usedIn: ['structural', 'rebar', 'sustainable']
        }
    ],
    
    // ============================================================================
    // TIER 7: ADVANCED & FUTURISTIC MATERIALS (8 recipes)
    // ============================================================================
    
    'Smart Materials': [
        {
            id: 'self_healing_concrete',
            name: 'Self-Healing Concrete',
            formula: 'Concrete + Bacteria + Calcium Lactate → Biological Repair',
            ingredients: { ConcreteMix: 30, Bacteria: 2, CalciumLactate: 5 },
            field: 'construction',
            category: 'Smart Materials',
            tier: 7,
            skillGain: 20,
            target: 800,
            icon: '🔄',
            unlocksAt: 6000,
            value: 300,
            description: 'Concrete that repairs its own cracks.',
            laborMultiplier: 2.0,
            usedIn: ['infrastructure', 'bridges', 'long_lasting']
        },
        {
            id: 'thermochromic_windows',
            name: 'Thermochromic Windows',
            formula: 'Glass + Thermochromic Coating → Smart Glass',
            ingredients: { FloatGlass: 20, ThermochromicCoating: 3 },
            field: 'construction',
            category: 'Smart Materials',
            tier: 7,
            skillGain: 18,
            target: 800,
            icon: '🪟',
            unlocksAt: 6200,
            value: 400,
            description: 'Windows that tint automatically in sunlight.',
            laborMultiplier: 2.0,
            usedIn: ['energy_efficient', 'commercial', 'high_end']
        },
        {
            id: 'electrochromic_glass',
            name: 'Electrochromic Glass',
            formula: 'Glass + Electrochromic Layer + Electrodes → Switchable',
            ingredients: { FloatGlass: 20, ElectrochromicLayer: 3, Electrodes: 2 },
            field: 'construction',
            category: 'Smart Materials',
            tier: 7,
            skillGain: 22,
            target: 800,
            icon: '⚡',
            unlocksAt: 6500,
            value: 600,
            description: 'Glass that tints on demand with electricity.',
            laborMultiplier: 2.3,
            usedIn: ['privacy', 'energy_savings', 'luxury']
        }
    ],
    
    'Aerospace-Grade': [
        {
            id: 'aerogel_insulation',
            name: 'Aerogel Insulation',
            formula: 'Silica + Supercritical Drying → Ultra-Low Density',
            ingredients: { Silica: 20, SupercriticalProcess: 1 },
            field: 'construction',
            category: 'Aerospace-Grade',
            tier: 7,
            skillGain: 25,
            target: 800,
            icon: '☁️',
            unlocksAt: 7000,
            value: 800,
            description: 'The world\'s best insulator, extremely lightweight.',
            laborMultiplier: 2.5,
            usedIn: ['space', 'high_performance', 'extreme']
        },
        {
            id: 'transparent_armor',
            name: 'Transparent Armor',
            formula: 'Glass + Polycarbonate + Ceramic → Ballistic',
            ingredients: { FloatGlass: 15, Polycarbonate: 10, AluminaCeramic: 5 },
            field: 'construction',
            category: 'Aerospace-Grade',
            tier: 7,
            skillGain: 28,
            target: 800,
            icon: '🛡️',
            unlocksAt: 7500,
            value: 1000,
            description: 'Bullet-resistant transparent material for security.',
            laborMultiplier: 2.8,
            usedIn: ['embassies', 'military', 'secure']
        }
    ],
    
    'Nanomaterials': [
        {
            id: 'carbon_nanotube_concrete',
            name: 'Carbon Nanotube Concrete',
            formula: 'Concrete + CNT Dispersion → Ultra-Strength',
            ingredients: { ConcreteMix: 40, CarbonNanotubes: 1 },
            field: 'construction',
            category: 'Nanomaterials',
            tier: 7,
            skillGain: 35,
            target: 800,
            icon: '🧪',
            unlocksAt: 8000,
            value: 1500,
            description: 'Concrete enhanced with carbon nanotubes for incredible strength.',
            laborMultiplier: 3.0,
            usedIn: ['superstructures', 'tallest_buildings', 'extreme']
        },
        {
            id: 'self_cleaning_coating',
            name: 'Self-Cleaning Coating',
            formula: 'TiO₂ + Silver + Hydrophobic → Photocatalytic',
            ingredients: { TitaniumDioxide: 10, Silver: 1, Silane: 2 },
            field: 'construction',
            category: 'Nanomaterials',
            tier: 7,
            skillGain: 20,
            target: 800,
            icon: '✨',
            unlocksAt: 7200,
            value: 300,
            description: 'Coating that breaks down dirt and stays clean.',
            laborMultiplier: 2.2,
            usedIn: ['facades', 'windows', 'maintenance_free']
        }
    ],
    
    // ============================================================================
    // ADDITIONAL: CONSTRUCTION COMPONENTS (Helper recipes)
    // ============================================================================
    
    'Fasteners & Hardware': [
        {
            id: 'nail',
            name: 'Nail',
            formula: 'Steel Wire → Forming → Nail',
            ingredients: { Steel: 5 },
            field: 'construction',
            category: 'Fasteners & Hardware',
            tier: 1,
            skillGain: 1,
            target: 100,
            icon: '🔨',
            unlocksAt: 0,
            value: 1,
            description: 'Basic fastener for wood construction.',
            laborMultiplier: 1.0,
            usedIn: ['framing', 'finishing', 'general']
        },
        {
            id: 'screw',
            name: 'Screw',
            formula: 'Steel + Threading → Screw',
            ingredients: { Steel: 3 },
            field: 'construction',
            category: 'Fasteners & Hardware',
            tier: 1,
            skillGain: 2,
            target: 100,
            icon: '🔩',
            unlocksAt: 50,
            value: 2,
            description: 'Threaded fastener for secure connections.',
            laborMultiplier: 1.1,
            usedIn: ['furniture', 'cabinetry', 'assembly']
        },
        {
            id: 'bolt',
            name: 'Bolt',
            formula: 'Steel + Threading + Head → Bolt',
            ingredients: { Steel: 5 },
            field: 'construction',
            category: 'Fasteners & Hardware',
            tier: 1,
            skillGain: 2,
            target: 100,
            icon: '⚙️',
            unlocksAt: 75,
            value: 3,
            description: 'Heavy-duty fastener for structural connections.',
            laborMultiplier: 1.1,
            usedIn: ['steel_connections', 'equipment', 'structural']
        },
        {
            id: 'anchor_bolt',
            name: 'Anchor Bolt',
            formula: 'Steel + Forming + Threading → Foundation Bolt',
            ingredients: { Steel: 8 },
            field: 'construction',
            category: 'Fasteners & Hardware',
            tier: 2,
            skillGain: 3,
            target: 200,
            icon: '📌',
            unlocksAt: 200,
            value: 5,
            description: 'Bolt for securing structures to concrete.',
            laborMultiplier: 1.2,
            usedIn: ['foundations', 'steel_columns', 'equipment']
        }
    ],
    
    'Windows & Doors': [
        {
            id: 'window_frame',
            name: 'Window Frame',
            formula: 'Extruded Aluminum or Wood → Frame',
            ingredients: { Aluminum: 15 },
            field: 'construction',
            category: 'Windows & Doors',
            tier: 3,
            skillGain: 5,
            target: 300,
            icon: '🪟',
            unlocksAt: 1200,
            value: 40,
            description: 'Frame for holding window glass.',
            laborMultiplier: 1.3,
            usedIn: ['windows', 'curtain_walls', 'glazing']
        },
        {
            id: 'door',
            name: 'Door',
            formula: 'Wood or Steel + Hardware → Door Assembly',
            ingredients: { Wood: 20, Hinges: 2, Handle: 1 },
            field: 'construction',
            category: 'Windows & Doors',
            tier: 3,
            skillGain: 6,
            target: 300,
            icon: '🚪',
            unlocksAt: 1250,
            value: 60,
            description: 'Complete door for interior or exterior use.',
            laborMultiplier: 1.4,
            usedIn: ['buildings', 'rooms', 'entrances']
        },
        {
            id: 'double_glazed_window',
            name: 'Double-Glazed Window',
            formula: 'Glass + Spacer + Gas Fill → Insulated Unit',
            ingredients: { FloatGlass: 15, Spacer: 2, ArgonGas: 1 },
            field: 'construction',
            category: 'Windows & Doors',
            tier: 4,
            skillGain: 8,
            target: 400,
            icon: '🪟',
            unlocksAt: 2000,
            value: 100,
            description: 'Energy-efficient window with two panes.',
            laborMultiplier: 1.5,
            usedIn: ['energy_efficient', 'homes', 'commercial']
        }
    ],
    
    'HVAC Components': [
        {
            id: 'ductwork',
            name: 'HVAC Ductwork',
            formula: 'Galvanized Steel + Forming → Air Ducts',
            ingredients: { GalvanizedSteel: 20 },
            field: 'construction',
            category: 'HVAC Components',
            tier: 3,
            skillGain: 5,
            target: 300,
            icon: '💨',
            unlocksAt: 1300,
            value: 30,
            description: 'Sheet metal ducts for air distribution.',
            laborMultiplier: 1.3,
            usedIn: ['heating', 'cooling', 'ventilation']
        },
        {
            id: 'insulated_pipe',
            name: 'Insulated Pipe',
            formula: 'Pipe + Foam Insulation + Jacket → Pre-Insulated',
            ingredients: { CopperPipe: 10, FoamInsulation: 5, PVCJacket: 2 },
            field: 'construction',
            category: 'HVAC Components',
            tier: 4,
            skillGain: 7,
            target: 400,
            icon: '🔧',
            unlocksAt: 1900,
            value: 45,
            description: 'Pipe with integrated insulation for plumbing and HVAC.',
            laborMultiplier: 1.4,
            usedIn: ['hot_water', 'chilled_water', 'refrigeration']
        }
    ]
};

// ============================================================================
// EXPORT ALL CONSTRUCTION RECIPES
// ============================================================================

export default CONSTRUCTION_RECIPES;
