// js/crafting/fields/metallurgy.js
// Metallurgy Recipes - 150+ recipes for advanced metalworking
// Tier 1-7: From Basic Smelting to Superalloys

export const METALLURGY_RECIPES = {
    
    // ============================================================================
    // TIER 1: BASIC METAL EXTRACTION (15 recipes)
    // ============================================================================
    
    'Basic Smelting': [
        {
            id: 'smelt_iron',
            name: 'Smelt Iron',
            formula: 'Fe₂O₃ + 3C → 2Fe + 3CO',
            ingredients: { IronOxide: 2, Carbon: 3 },
            field: 'metallurgy',
            category: 'Basic Smelting',
            tier: 1,
            skillGain: 2,
            target: 100,
            icon: '⚙️',
            unlocksAt: 0,
            value: 50,
            description: 'Extract iron from iron oxide using carbon.',
            laborMultiplier: 1.1,
            usedIn: ['steel', 'cast_iron', 'tools']
        },
        {
            id: 'smelt_copper',
            name: 'Smelt Copper',
            formula: 'Cu₂O + C → 2Cu + CO',
            ingredients: { CopperOxide: 2, Carbon: 1 },
            field: 'metallurgy',
            category: 'Basic Smelting',
            tier: 1,
            skillGain: 2,
            target: 100,
            icon: '🔴',
            unlocksAt: 0,
            value: 60,
            description: 'Extract copper from copper oxide.',
            laborMultiplier: 1.1,
            usedIn: ['bronze', 'brass', 'electrical']
        },
        {
            id: 'smelt_tin',
            name: 'Smelt Tin',
            formula: 'SnO₂ + 2C → Sn + 2CO',
            ingredients: { TinOxide: 1, Carbon: 2 },
            field: 'metallurgy',
            category: 'Basic Smelting',
            tier: 1,
            skillGain: 2,
            target: 100,
            icon: '⚪',
            unlocksAt: 0,
            value: 80,
            description: 'Extract tin from cassiterite.',
            laborMultiplier: 1.1,
            usedIn: ['bronze', 'solder', 'coatings']
        },
        {
            id: 'smelt_zinc',
            name: 'Smelt Zinc',
            formula: 'ZnO + C → Zn + CO',
            ingredients: { ZincOxide: 1, Carbon: 1 },
            field: 'metallurgy',
            category: 'Basic Smelting',
            tier: 1,
            skillGain: 2,
            target: 100,
            icon: '⚪',
            unlocksAt: 10,
            value: 70,
            description: 'Extract zinc from zinc oxide.',
            laborMultiplier: 1.1,
            usedIn: ['brass', 'galvanization', 'die_casting']
        },
        {
            id: 'smelt_lead',
            name: 'Smelt Lead',
            formula: 'PbS + O₂ → Pb + SO₂',
            ingredients: { LeadSulfide: 1, Oxygen: 1 },
            field: 'metallurgy',
            category: 'Basic Smelting',
            tier: 1,
            skillGain: 2,
            target: 100,
            icon: '⚖️',
            unlocksAt: 20,
            value: 60,
            description: 'Extract lead from galena.',
            laborMultiplier: 1.1,
            usedIn: ['batteries', 'radiation_shielding', 'solder']
        },
        {
            id: 'smelt_nickel',
            name: 'Smelt Nickel',
            formula: 'NiO + C → Ni + CO',
            ingredients: { NickelOxide: 1, Carbon: 1 },
            field: 'metallurgy',
            category: 'Basic Smelting',
            tier: 1,
            skillGain: 3,
            target: 100,
            icon: '🔩',
            unlocksAt: 30,
            value: 100,
            description: 'Extract nickel from nickel oxide.',
            laborMultiplier: 1.2,
            usedIn: ['stainless_steel', 'superalloys', 'coinage']
        },
        {
            id: 'smelt_aluminum',
            name: 'Smelt Aluminum',
            formula: 'Al₂O₃ + 3C → 2Al + 3CO',
            ingredients: { AluminumOxide: 2, Carbon: 3 },
            field: 'metallurgy',
            category: 'Basic Smelting',
            tier: 1,
            skillGain: 4,
            target: 100,
            icon: '🥫',
            unlocksAt: 40,
            value: 120,
            description: 'Extract aluminum from alumina. Energy intensive.',
            laborMultiplier: 1.3,
            usedIn: ['duralumin', 'aerospace', 'packaging']
        },
        {
            id: 'smelt_titanium',
            name: 'Smelt Titanium',
            formula: 'TiO₂ + 2C + 2Cl₂ → TiCl₄ + 2CO → Ti',
            ingredients: { TitaniumOxide: 1, Carbon: 2, Chlorine: 2 },
            field: 'metallurgy',
            category: 'Basic Smelting',
            tier: 1,
            skillGain: 5,
            target: 100,
            icon: '🔷',
            unlocksAt: 50,
            value: 200,
            description: 'Extract titanium via the Kroll process.',
            laborMultiplier: 1.5,
            usedIn: ['aerospace', 'medical_implants', 'high_performance']
        },
        {
            id: 'smelt_magnesium',
            name: 'Smelt Magnesium',
            formula: 'MgO + C → Mg + CO',
            ingredients: { MagnesiumOxide: 1, Carbon: 1 },
            field: 'metallurgy',
            category: 'Basic Smelting',
            tier: 1,
            skillGain: 2,
            target: 100,
            icon: '✨',
            unlocksAt: 60,
            value: 90,
            description: 'Extract magnesium from magnesia.',
            laborMultiplier: 1.2,
            usedIn: ['alloys', 'pyrotechnics', 'lightweight']
        },
        {
            id: 'smelt_chromium',
            name: 'Smelt Chromium',
            formula: 'Cr₂O₃ + 3C → 2Cr + 3CO',
            ingredients: { ChromiumOxide: 2, Carbon: 3 },
            field: 'metallurgy',
            category: 'Basic Smelting',
            tier: 1,
            skillGain: 3,
            target: 100,
            icon: '🔩',
            unlocksAt: 70,
            value: 150,
            description: 'Extract chromium from chromite.',
            laborMultiplier: 1.3,
            usedIn: ['stainless_steel', 'plating', 'superalloys']
        },
        {
            id: 'smelt_manganese',
            name: 'Smelt Manganese',
            formula: 'MnO₂ + 2C → Mn + 2CO',
            ingredients: { ManganeseOxide: 1, Carbon: 2 },
            field: 'metallurgy',
            category: 'Basic Smelting',
            tier: 1,
            skillGain: 2,
            target: 100,
            icon: '⚙️',
            unlocksAt: 80,
            value: 80,
            description: 'Extract manganese from pyrolusite.',
            laborMultiplier: 1.2,
            usedIn: ['steel', 'aluminum_alloys', 'batteries']
        },
        {
            id: 'smelt_cobalt',
            name: 'Smelt Cobalt',
            formula: 'CoO + C → Co + CO',
            ingredients: { CobaltOxide: 1, Carbon: 1 },
            field: 'metallurgy',
            category: 'Basic Smelting',
            tier: 1,
            skillGain: 3,
            target: 100,
            icon: '🔵',
            unlocksAt: 90,
            value: 200,
            description: 'Extract cobalt from cobalt oxide.',
            laborMultiplier: 1.3,
            usedIn: ['superalloys', 'batteries', 'magnets']
        },
        {
            id: 'smelt_tungsten',
            name: 'Smelt Tungsten',
            formula: 'WO₃ + 3C → W + 3CO',
            ingredients: { TungstenOxide: 1, Carbon: 3 },
            field: 'metallurgy',
            category: 'Basic Smelting',
            tier: 1,
            skillGain: 5,
            target: 100,
            icon: '⚡',
            unlocksAt: 100,
            value: 300,
            description: 'Extract tungsten from wolframite.',
            laborMultiplier: 1.5,
            usedIn: ['carbide', 'filaments', 'alloys']
        },
        {
            id: 'smelt_vanadium',
            name: 'Smelt Vanadium',
            formula: 'V₂O₅ + 5C → 2V + 5CO',
            ingredients: { VanadiumOxide: 2, Carbon: 5 },
            field: 'metallurgy',
            category: 'Basic Smelting',
            tier: 1,
            skillGain: 4,
            target: 100,
            icon: '🔧',
            unlocksAt: 110,
            value: 250,
            description: 'Extract vanadium from vanadium pentoxide.',
            laborMultiplier: 1.4,
            usedIn: ['steel', 'titanium_alloys', 'batteries']
        },
        {
            id: 'smelt_molybdenum',
            name: 'Smelt Molybdenum',
            formula: 'MoO₃ + 3C → Mo + 3CO',
            ingredients: { MolybdenumOxide: 1, Carbon: 3 },
            field: 'metallurgy',
            category: 'Basic Smelting',
            tier: 1,
            skillGain: 4,
            target: 100,
            icon: '🔩',
            unlocksAt: 120,
            value: 280,
            description: 'Extract molybdenum from molybdenite.',
            laborMultiplier: 1.4,
            usedIn: ['steel', 'superalloys', 'lubricants']
        }
    ],
    
    'Ore Processing': [
        {
            id: 'crush_iron_ore',
            name: 'Crush Iron Ore',
            formula: 'Fe₂O₃ (ore) → Fe₂O₃ (concentrate)',
            ingredients: { IronOre: 2 },
            field: 'metallurgy',
            category: 'Ore Processing',
            tier: 1,
            skillGain: 1,
            target: 100,
            icon: '⛏️',
            unlocksAt: 0,
            value: 20,
            description: 'Crush iron ore to prepare for smelting.',
            laborMultiplier: 1.0,
            usedIn: ['smelt_iron']
        },
        {
            id: 'crush_copper_ore',
            name: 'Crush Copper Ore',
            formula: 'Cu₂O (ore) → Cu₂O (concentrate)',
            ingredients: { CopperOre: 2 },
            field: 'metallurgy',
            category: 'Ore Processing',
            tier: 1,
            skillGain: 1,
            target: 100,
            icon: '⛏️',
            unlocksAt: 0,
            value: 25,
            description: 'Crush copper ore to prepare for smelting.',
            laborMultiplier: 1.0,
            usedIn: ['smelt_copper']
        },
        {
            id: 'roast_sulfide_ore',
            name: 'Roast Sulfide Ore',
            formula: '2PbS + 3O₂ → 2PbO + 2SO₂',
            ingredients: { LeadSulfide: 2, Oxygen: 3 },
            field: 'metallurgy',
            category: 'Ore Processing',
            tier: 1,
            skillGain: 3,
            target: 100,
            icon: '🔥',
            unlocksAt: 50,
            value: 40,
            description: 'Roast sulfide ores to convert to oxides.',
            laborMultiplier: 1.2,
            usedIn: ['smelt_lead', 'smelt_zinc']
        },
        {
            id: 'concentrate_magnetic',
            name: 'Magnetic Concentration',
            formula: 'Fe₃O₄ (ore) → Magnetic Separation',
            ingredients: { MagnetiteOre: 2 },
            field: 'metallurgy',
            category: 'Ore Processing',
            tier: 1,
            skillGain: 2,
            target: 100,
            icon: '🧲',
            unlocksAt: 80,
            value: 35,
            description: 'Use magnets to concentrate iron ore.',
            laborMultiplier: 1.1,
            usedIn: ['smelt_iron']
        },
        {
            id: 'froth_flotation',
            name: 'Froth Flotation',
            formula: 'Ore + Chemicals → Concentrate',
            ingredients: { SulfideOre: 2, Water: 1, PineOil: 1 },
            field: 'metallurgy',
            category: 'Ore Processing',
            tier: 1,
            skillGain: 4,
            target: 100,
            icon: '🫧',
            unlocksAt: 100,
            value: 50,
            description: 'Separate valuable minerals using bubbles.',
            laborMultiplier: 1.3,
            usedIn: ['copper_concentrate', 'zinc_concentrate']
        }
    ],
    
    // ============================================================================
    // TIER 2: BINARY ALLOYS (25 recipes)
    // ============================================================================
    
    'Copper Alloys': [
        {
            id: 'bronze_90_10',
            name: 'Bronze (90/10)',
            formula: '9Cu + 1Sn → Cu₉Sn',
            ingredients: { Copper: 9, Tin: 1 },
            field: 'metallurgy',
            category: 'Copper Alloys',
            tier: 2,
            skillGain: 5,
            target: 200,
            icon: '🏺',
            unlocksAt: 200,
            value: 150,
            description: 'Standard bronze - harder than copper, corrosion resistant.',
            laborMultiplier: 1.3,
            usedIn: ['bearings', 'bushings', 'art']
        },
        {
            id: 'bronze_80_20',
            name: 'Bronze (80/20)',
            formula: '4Cu + 1Sn → Cu₄Sn',
            ingredients: { Copper: 4, Tin: 1 },
            field: 'metallurgy',
            category: 'Copper Alloys',
            tier: 2,
            skillGain: 6,
            target: 200,
            icon: '🏺',
            unlocksAt: 250,
            value: 180,
            description: 'High-tin bronze - harder, used for bells and mirrors.',
            laborMultiplier: 1.4,
            usedIn: ['bells', 'mirrors', 'tools']
        },
        {
            id: 'bronze_95_5',
            name: 'Bronze (95/5)',
            formula: '19Cu + 1Sn → Cu₁₉Sn',
            ingredients: { Copper: 19, Tin: 1 },
            field: 'metallurgy',
            category: 'Copper Alloys',
            tier: 2,
            skillGain: 4,
            target: 200,
            icon: '🏺',
            unlocksAt: 220,
            value: 140,
            description: 'Low-tin bronze - more ductile, easier to work.',
            laborMultiplier: 1.2,
            usedIn: ['coins', 'jewelry', 'sheet']
        },
        {
            id: 'brass_70_30',
            name: 'Brass (70/30)',
            formula: '7Cu + 3Zn → Cu₇Zn₃',
            ingredients: { Copper: 7, Zinc: 3 },
            field: 'metallurgy',
            category: 'Copper Alloys',
            tier: 2,
            skillGain: 5,
            target: 200,
            icon: '🔔',
            unlocksAt: 300,
            value: 160,
            description: 'Cartridge brass - excellent cold working properties.',
            laborMultiplier: 1.3,
            usedIn: ['ammunition', 'radiators', 'fittings']
        },
        {
            id: 'brass_60_40',
            name: 'Brass (60/40)',
            formula: '3Cu + 2Zn → Cu₃Zn₂',
            ingredients: { Copper: 3, Zinc: 2 },
            field: 'metallurgy',
            category: 'Copper Alloys',
            tier: 2,
            skillGain: 5,
            target: 200,
            icon: '🔔',
            unlocksAt: 320,
            value: 170,
            description: 'Muntz metal - hot working brass for large parts.',
            laborMultiplier: 1.3,
            usedIn: ['marine_fittings', 'valves', 'condensers']
        },
        {
            id: 'cupronickel_90_10',
            name: 'Cupronickel (90/10)',
            formula: '9Cu + 1Ni → Cu₉Ni',
            ingredients: { Copper: 9, Nickel: 1 },
            field: 'metallurgy',
            category: 'Copper Alloys',
            tier: 2,
            skillGain: 6,
            target: 200,
            icon: '🪙',
            unlocksAt: 350,
            value: 200,
            description: 'Corrosion-resistant alloy for marine applications.',
            laborMultiplier: 1.4,
            usedIn: ['ship_hulls', 'desalination', 'coinage']
        },
        {
            id: 'cupronickel_70_30',
            name: 'Cupronickel (70/30)',
            formula: '7Cu + 3Ni → Cu₇Ni₃',
            ingredients: { Copper: 7, Nickel: 3 },
            field: 'metallurgy',
            category: 'Copper Alloys',
            tier: 2,
            skillGain: 7,
            target: 200,
            icon: '🪙',
            unlocksAt: 400,
            value: 250,
            description: 'High-strength cupronickel for condenser tubes.',
            laborMultiplier: 1.5,
            usedIn: ['condensers', 'heat_exchangers', 'piping']
        },
        {
            id: 'beryllium_copper',
            name: 'Beryllium Copper',
            formula: 'Cu + 0.02Be → CuBe',
            ingredients: { Copper: 50, Beryllium: 1 },
            field: 'metallurgy',
            category: 'Copper Alloys',
            tier: 2,
            skillGain: 10,
            target: 200,
            icon: '⚡',
            unlocksAt: 500,
            value: 500,
            description: 'High-strength, non-sparking alloy for tools.',
            laborMultiplier: 1.8,
            usedIn: ['tools', 'springs', 'electrical_contacts']
        }
    ],
    
    'Iron Alloys': [
        {
            id: 'cast_iron',
            name: 'Cast Iron',
            formula: 'Fe + 0.04C → Fe₉₆C₄',
            ingredients: { Iron: 24, Carbon: 1 },
            field: 'metallurgy',
            category: 'Iron Alloys',
            tier: 2,
            skillGain: 4,
            target: 200,
            icon: '🏋️',
            unlocksAt: 200,
            value: 100,
            description: 'High-carbon iron, castable but brittle.',
            laborMultiplier: 1.2,
            usedIn: ['engine_blocks', 'pipes', 'cookware']
        },
        {
            id: 'wrought_iron',
            name: 'Wrought Iron',
            formula: 'Fe + 0.01C + Slag → Fibrous Fe',
            ingredients: { Iron: 50, Carbon: 1, Slag: 5 },
            field: 'metallurgy',
            category: 'Iron Alloys',
            tier: 2,
            skillGain: 5,
            target: 200,
            icon: '🔨',
            unlocksAt: 250,
            value: 120,
            description: 'Low-carbon iron, tough and weldable.',
            laborMultiplier: 1.3,
            usedIn: ['gates', 'railings', 'chains']
        },
        {
            id: 'pig_iron',
            name: 'Pig Iron',
            formula: 'Fe + C + Impurities → Crude Fe',
            ingredients: { Iron: 10, Carbon: 2, Limestone: 1 },
            field: 'metallurgy',
            category: 'Iron Alloys',
            tier: 2,
            skillGain: 3,
            target: 200,
            icon: '🐖',
            unlocksAt: 220,
            value: 80,
            description: 'Crude iron from blast furnace, intermediate product.',
            laborMultiplier: 1.1,
            usedIn: ['steel', 'cast_iron']
        }
    ],
    
    'Aluminum Alloys': [
        {
            id: 'aluminum_silicon',
            name: 'Aluminum-Silicon',
            formula: 'Al + 0.12Si → Al₈₈Si₁₂',
            ingredients: { Aluminum: 22, Silicon: 3 },
            field: 'metallurgy',
            category: 'Aluminum Alloys',
            tier: 2,
            skillGain: 4,
            target: 200,
            icon: '🥫',
            unlocksAt: 400,
            value: 180,
            description: 'Good castability, used for pistons.',
            laborMultiplier: 1.3,
            usedIn: ['pistons', 'castings', 'engine_parts']
        },
        {
            id: 'aluminum_magnesium',
            name: 'Aluminum-Magnesium',
            formula: 'Al + 0.05Mg → Al₉₅Mg₅',
            ingredients: { Aluminum: 19, Magnesium: 1 },
            field: 'metallurgy',
            category: 'Aluminum Alloys',
            tier: 2,
            skillGain: 4,
            target: 200,
            icon: '✨',
            unlocksAt: 420,
            value: 200,
            description: 'Good corrosion resistance, weldable.',
            laborMultiplier: 1.3,
            usedIn: ['marine', 'architectural', 'tanks']
        }
    ],
    
    'Nickel Alloys': [
        {
            id: 'nickel_iron',
            name: 'Nickel-Iron (Invar)',
            formula: 'Ni + 0.36Fe → Ni₆₄Fe₃₆',
            ingredients: { Nickel: 16, Iron: 9 },
            field: 'metallurgy',
            category: 'Nickel Alloys',
            tier: 2,
            skillGain: 8,
            target: 200,
            icon: '📏',
            unlocksAt: 500,
            value: 400,
            description: 'Low thermal expansion alloy for precision instruments.',
            laborMultiplier: 1.6,
            usedIn: ['instruments', 'lasers', 'scientific']
        },
        {
            id: 'nickel_copper',
            name: 'Nickel-Copper (Monel)',
            formula: 'Ni + 0.3Cu → Ni₇₀Cu₃₀',
            ingredients: { Nickel: 7, Copper: 3 },
            field: 'metallurgy',
            category: 'Nickel Alloys',
            tier: 2,
            skillGain: 7,
            target: 200,
            icon: '🔧',
            unlocksAt: 550,
            value: 350,
            description: 'Corrosion-resistant alloy for marine hardware.',
            laborMultiplier: 1.5,
            usedIn: ['valves', 'pumps', 'marine']
        }
    ],
    
    // ============================================================================
    // TIER 3: TERNARY ALLOYS & STAINLESS STEELS (30 recipes)
    // ============================================================================
    
    'Stainless Steels': [
        {
            id: 'stainless_304',
            name: 'Stainless Steel 304',
            formula: 'Fe + 0.18Cr + 0.08Ni → Fe₇₄Cr₁₈Ni₈',
            ingredients: { Iron: 74, Chromium: 18, Nickel: 8 },
            field: 'metallurgy',
            category: 'Stainless Steels',
            tier: 3,
            skillGain: 15,
            target: 300,
            icon: '🥄',
            unlocksAt: 800,
            value: 500,
            description: 'Austenitic stainless, most common grade.',
            laborMultiplier: 1.8,
            usedIn: ['kitchenware', 'architecture', 'food_processing']
        },
        {
            id: 'stainless_316',
            name: 'Stainless Steel 316',
            formula: 'Fe + 0.16Cr + 0.10Ni + 0.02Mo → Fe₇₂Cr₁₆Ni₁₀Mo₂',
            ingredients: { Iron: 72, Chromium: 16, Nickel: 10, Molybdenum: 2 },
            field: 'metallurgy',
            category: 'Stainless Steels',
            tier: 3,
            skillGain: 18,
            target: 300,
            icon: '⚓',
            unlocksAt: 900,
            value: 650,
            description: 'Marine grade with molybdenum for pitting resistance.',
            laborMultiplier: 2.0,
            usedIn: ['marine', 'chemical', 'medical_implants']
        },
        {
            id: 'stainless_321',
            name: 'Stainless Steel 321',
            formula: 'Fe + 0.17Cr + 0.09Ni + 0.004Ti → Fe₇₂Cr₁₇Ni₉Ti',
            ingredients: { Iron: 72, Chromium: 17, Nickel: 9, Titanium: 1 },
            field: 'metallurgy',
            category: 'Stainless Steels',
            tier: 3,
            skillGain: 17,
            target: 300,
            icon: '🔥',
            unlocksAt: 950,
            value: 600,
            description: 'Stabilized with titanium for high-temperature use.',
            laborMultiplier: 1.9,
            usedIn: ['aircraft', 'exhaust', 'heat_exchangers']
        },
        {
            id: 'stainless_347',
            name: 'Stainless Steel 347',
            formula: 'Fe + 0.17Cr + 0.11Ni + 0.01Nb → Fe₇₁Cr₁₇Ni₁₁Nb',
            ingredients: { Iron: 71, Chromium: 17, Nickel: 11, Niobium: 1 },
            field: 'metallurgy',
            category: 'Stainless Steels',
            tier: 3,
            skillGain: 18,
            target: 300,
            icon: '🔥',
            unlocksAt: 1000,
            value: 620,
            description: 'Stabilized with niobium for welding applications.',
            laborMultiplier: 2.0,
            usedIn: ['welded_structures', 'nuclear', 'chemical']
        },
        {
            id: 'stainless_410',
            name: 'Stainless Steel 410',
            formula: 'Fe + 0.115Cr → Fe₈₅Cr₁₁₅',
            ingredients: { Iron: 85, Chromium: 12 },
            field: 'metallurgy',
            category: 'Stainless Steels',
            tier: 3,
            skillGain: 12,
            target: 300,
            icon: '🔪',
            unlocksAt: 850,
            value: 450,
            description: 'Martensitic stainless, hardenable.',
            laborMultiplier: 1.7,
            usedIn: ['cutlery', 'valves', 'pumps']
        },
        {
            id: 'stainless_430',
            name: 'Stainless Steel 430',
            formula: 'Fe + 0.16Cr → Fe₈₄Cr₁₆',
            ingredients: { Iron: 84, Chromium: 16 },
            field: 'metallurgy',
            category: 'Stainless Steels',
            tier: 3,
            skillGain: 12,
            target: 300,
            icon: '🧲',
            unlocksAt: 880,
            value: 420,
            description: 'Ferritic stainless, magnetic, good formability.',
            laborMultiplier: 1.7,
            usedIn: ['appliances', 'automotive', 'trim']
        },
        {
            id: 'stainless_2205',
            name: 'Duplex Stainless 2205',
            formula: 'Fe + 0.22Cr + 0.05Ni + 0.03Mo → Fe₇₀Cr₂₂Ni₅Mo₃',
            ingredients: { Iron: 70, Chromium: 22, Nickel: 5, Molybdenum: 3 },
            field: 'metallurgy',
            category: 'Stainless Steels',
            tier: 3,
            skillGain: 22,
            target: 300,
            icon: '⚔️',
            unlocksAt: 1200,
            value: 800,
            description: 'Duplex stainless with high strength and corrosion resistance.',
            laborMultiplier: 2.2,
            usedIn: ['offshore', 'chemical_tankers', 'bridges']
        }
    ],
    
    'Tool Steels': [
        {
            id: 'tool_steel_d2',
            name: 'Tool Steel D2',
            formula: 'Fe + 0.15C + 0.12Cr + 0.01Mo + 0.01V → High-Carbon',
            ingredients: { Iron: 70, Carbon: 15, Chromium: 12, Molybdenum: 1, Vanadium: 1 },
            field: 'metallurgy',
            category: 'Tool Steels',
            tier: 3,
            skillGain: 20,
            target: 300,
            icon: '🔪',
            unlocksAt: 1300,
            value: 700,
            description: 'High-carbon, high-chromium tool steel for long runs.',
            laborMultiplier: 2.1,
            usedIn: ['dies', 'cutters', 'shears']
        },
        {
            id: 'tool_steel_o1',
            name: 'Tool Steel O1',
            formula: 'Fe + 0.01C + 0.005Mn + 0.005W → Oil-Hardening',
            ingredients: { Iron: 80, Carbon: 10, Manganese: 5, Tungsten: 5 },
            field: 'metallurgy',
            category: 'Tool Steels',
            tier: 3,
            skillGain: 18,
            target: 300,
            icon: '🔧',
            unlocksAt: 1250,
            value: 600,
            description: 'Oil-hardening tool steel, good for general use.',
            laborMultiplier: 2.0,
            usedIn: ['tools', 'dies', 'gauges']
        },
        {
            id: 'tool_steel_a2',
            name: 'Tool Steel A2',
            formula: 'Fe + 0.01C + 0.05Cr + 0.01Mo + 0.01V → Air-Hardening',
            ingredients: { Iron: 75, Carbon: 10, Chromium: 5, Molybdenum: 5, Vanadium: 5 },
            field: 'metallurgy',
            category: 'Tool Steels',
            tier: 3,
            skillGain: 19,
            target: 300,
            icon: '🔨',
            unlocksAt: 1350,
            value: 650,
            description: 'Air-hardening tool steel, good wear resistance.',
            laborMultiplier: 2.1,
            usedIn: ['punches', 'dies', 'molds']
        },
        {
            id: 'tool_steel_m2',
            name: 'High-Speed Steel M2',
            formula: 'Fe + 0.01C + 0.04Cr + 0.05W + 0.02Mo + 0.02V → HSS',
            ingredients: { Iron: 60, Carbon: 10, Chromium: 4, Tungsten: 6, Molybdenum: 5, Vanadium: 2 },
            field: 'metallurgy',
            category: 'Tool Steels',
            tier: 3,
            skillGain: 25,
            target: 300,
            icon: '⚡',
            unlocksAt: 1500,
            value: 900,
            description: 'High-speed steel for cutting tools at high temperatures.',
            laborMultiplier: 2.5,
            usedIn: ['drills', 'end_mills', 'saw_blades']
        },
        {
            id: 'tool_steel_h13',
            name: 'Hot Work Steel H13',
            formula: 'Fe + 0.004C + 0.05Cr + 0.01Mo + 0.01V → Hot-Work',
            ingredients: { Iron: 75, Carbon: 4, Chromium: 5, Molybdenum: 5, Vanadium: 5 },
            field: 'metallurgy',
            category: 'Tool Steels',
            tier: 3,
            skillGain: 22,
            target: 300,
            icon: '🔥',
            unlocksAt: 1400,
            value: 750,
            description: 'Hot-work steel for die casting and extrusion.',
            laborMultiplier: 2.3,
            usedIn: ['die_casting', 'extrusion', 'forging']
        }
    ],
    
    // ============================================================================
    // TIER 4: HEAT TREATMENT PROCESSES (20 recipes)
    // ============================================================================
    
    'Heat Treatment': [
        {
            id: 'anneal_steel',
            name: 'Annealing (Steel)',
            formula: 'Heat → Hold → Slow Cool → Softened',
            ingredients: { Steel: 10 },
            field: 'metallurgy',
            category: 'Heat Treatment',
            tier: 4,
            skillGain: 5,
            target: 500,
            icon: '🔥',
            unlocksAt: 2000,
            value: 100,
            description: 'Softens steel for easier machining.',
            laborMultiplier: 1.3,
            usedIn: ['machining', 'cold_working', 'forming']
        },
        {
            id: 'normalize_steel',
            name: 'Normalizing',
            formula: 'Heat → Air Cool → Refined Grain',
            ingredients: { Steel: 10 },
            field: 'metallurgy',
            category: 'Heat Treatment',
            tier: 4,
            skillGain: 6,
            target: 500,
            icon: '🌬️',
            unlocksAt: 2100,
            value: 120,
            description: 'Refines grain structure for uniform properties.',
            laborMultiplier: 1.4,
            usedIn: ['structural', 'forgings', 'castings']
        },
        {
            id: 'quench_oil',
            name: 'Oil Quenching',
            formula: 'Heat → Oil Quench → Hardened',
            ingredients: { Steel: 10, Oil: 5 },
            field: 'metallurgy',
            category: 'Heat Treatment',
            tier: 4,
            skillGain: 8,
            target: 500,
            icon: '💧',
            unlocksAt: 2200,
            value: 150,
            description: 'Oil quenching for controlled hardening.',
            laborMultiplier: 1.5,
            usedIn: ['tools', 'springs', 'wear_parts']
        },
        {
            id: 'quench_water',
            name: 'Water Quenching',
            formula: 'Heat → Water Quench → Maximum Hardness',
            ingredients: { Steel: 10, Water: 10 },
            field: 'metallurgy',
            category: 'Heat Treatment',
            tier: 4,
            skillGain: 9,
            target: 500,
            icon: '💦',
            unlocksAt: 2300,
            value: 140,
            description: 'Water quenching for maximum hardness, risk of cracking.',
            laborMultiplier: 1.5,
            usedIn: ['simple_shapes', 'high_hardness']
        },
        {
            id: 'quench_brine',
            name: 'Brine Quenching',
            formula: 'Heat → Brine Quench → Very Fast',
            ingredients: { Steel: 10, SaltWater: 10 },
            field: 'metallurgy',
            category: 'Heat Treatment',
            tier: 4,
            skillGain: 10,
            target: 500,
            icon: '🧂',
            unlocksAt: 2400,
            value: 160,
            description: 'Brine quenching for fastest cooling rate.',
            laborMultiplier: 1.6,
            usedIn: ['carbon_steels', 'uniform_hardening']
        },
        {
            id: 'temper_low',
            name: 'Low Temperature Tempering',
            formula: 'Heat to 150-200°C → Hold → Toughness',
            ingredients: { HardenedSteel: 10 },
            field: 'metallurgy',
            category: 'Heat Treatment',
            tier: 4,
            skillGain: 7,
            target: 500,
            icon: '🔥',
            unlocksAt: 2500,
            value: 130,
            description: 'Low temper for hardness with some toughness.',
            laborMultiplier: 1.4,
            usedIn: ['cutting_tools', 'dies']
        },
        {
            id: 'temper_medium',
            name: 'Medium Temperature Tempering',
            formula: 'Heat to 350-450°C → Hold → Spring Temper',
            ingredients: { HardenedSteel: 10 },
            field: 'metallurgy',
            category: 'Heat Treatment',
            tier: 4,
            skillGain: 8,
            target: 500,
            icon: '🔥',
            unlocksAt: 2600,
            value: 140,
            description: 'Medium temper for spring properties.',
            laborMultiplier: 1.5,
            usedIn: ['springs', 'shock_absorbers']
        },
        {
            id: 'temper_high',
            name: 'High Temperature Tempering',
            formula: 'Heat to 550-650°C → Hold → Toughness',
            ingredients: { HardenedSteel: 10 },
            field: 'metallurgy',
            category: 'Heat Treatment',
            tier: 4,
            skillGain: 9,
            target: 500,
            icon: '🔥',
            unlocksAt: 2700,
            value: 150,
            description: 'High temper for maximum toughness.',
            laborMultiplier: 1.6,
            usedIn: ['structural', 'machine_parts']
        },
        {
            id: 'carburize',
            name: 'Carburizing',
            formula: 'Low-C Steel + Carbon → High-C Surface',
            ingredients: { LowCarbonSteel: 10, Carbon: 5 },
            field: 'metallurgy',
            category: 'Heat Treatment',
            tier: 4,
            skillGain: 15,
            target: 500,
            icon: '⚫',
            unlocksAt: 3000,
            value: 200,
            description: 'Adds carbon to surface for wear resistance.',
            laborMultiplier: 1.8,
            usedIn: ['gears', 'bearings', 'cams']
        },
        {
            id: 'nitride',
            name: 'Nitriding',
            formula: 'Steel + Nitrogen → Hard Surface',
            ingredients: { AlloySteel: 10, Ammonia: 10 },
            field: 'metallurgy',
            category: 'Heat Treatment',
            tier: 4,
            skillGain: 18,
            target: 500,
            icon: '💨',
            unlocksAt: 3500,
            value: 250,
            description: 'Nitrogen diffusion for extremely hard surface.',
            laborMultiplier: 2.0,
            usedIn: ['crankshafts', 'cylinder_liners', 'dies']
        }
    ],
    
    // ============================================================================
    // TIER 5: SUPERALLOYS (25 recipes)
    // ============================================================================
    
    'Nickel Superalloys': [
        {
            id: 'inconel_600',
            name: 'Inconel 600',
            formula: 'Ni + 0.15Cr + 0.08Fe → Ni₇₂Cr₁₅Fe₈',
            ingredients: { Nickel: 72, Chromium: 15, Iron: 8 },
            field: 'metallurgy',
            category: 'Nickel Superalloys',
            tier: 5,
            skillGain: 30,
            target: 1000,
            icon: '🔥',
            unlocksAt: 5000,
            value: 1500,
            description: 'Nickel-chromium alloy for high-temperature service.',
            laborMultiplier: 2.5,
            usedIn: ['furnace_parts', 'heat_treating', 'chemical']
        },
        {
            id: 'inconel_625',
            name: 'Inconel 625',
            formula: 'Ni + 0.21Cr + 0.09Mo + 0.04Nb → Ni₆₁Cr₂₁Mo₉Nb₄',
            ingredients: { Nickel: 61, Chromium: 21, Molybdenum: 9, Niobium: 4 },
            field: 'metallurgy',
            category: 'Nickel Superalloys',
            tier: 5,
            skillGain: 40,
            target: 1000,
            icon: '⚓',
            unlocksAt: 6000,
            value: 2000,
            description: 'High strength, excellent corrosion resistance.',
            laborMultiplier: 3.0,
            usedIn: ['marine', 'aerospace', 'chemical']
        },
        {
            id: 'inconel_718',
            name: 'Inconel 718',
            formula: 'Ni + 0.19Cr + 0.18Fe + 0.05Nb + 0.03Mo → Ni₅₀Cr₁₉Fe₁₈Nb₅Mo₃',
            ingredients: { Nickel: 50, Chromium: 19, Iron: 18, Niobium: 5, Molybdenum: 3 },
            field: 'metallurgy',
            category: 'Nickel Superalloys',
            tier: 5,
            skillGain: 50,
            target: 1000,
            icon: '🚀',
            unlocksAt: 7000,
            value: 2500,
            description: 'Precipitation-hardenable superalloy for jet engines.',
            laborMultiplier: 3.5,
            usedIn: ['jet_engines', 'turbines', 'rocket']
        },
        {
            id: 'hastelloy_c276',
            name: 'Hastelloy C-276',
            formula: 'Ni + 0.16Mo + 0.15Cr + 0.05Fe + 0.04W → Ni₅₇Mo₁₆Cr₁₅Fe₅W₄',
            ingredients: { Nickel: 57, Molybdenum: 16, Chromium: 15, Iron: 5, Tungsten: 4 },
            field: 'metallurgy',
            category: 'Nickel Superalloys',
            tier: 5,
            skillGain: 55,
            target: 1000,
            icon: '☣️',
            unlocksAt: 8000,
            value: 3000,
            description: 'Extreme corrosion resistance for chemical processing.',
            laborMultiplier: 4.0,
            usedIn: ['chemical_reactors', 'scrubbers', 'pollution_control']
        },
        {
            id: 'waspaloy',
            name: 'Waspaloy',
            formula: 'Ni + 0.19Cr + 0.13Co + 0.04Mo + 0.03Ti + 0.01Al → Complex',
            ingredients: { Nickel: 57, Chromium: 19, Cobalt: 13, Molybdenum: 4, Titanium: 3, Aluminum: 1 },
            field: 'metallurgy',
            category: 'Nickel Superalloys',
            tier: 5,
            skillGain: 60,
            target: 1000,
            icon: '⚡',
            unlocksAt: 9000,
            value: 3500,
            description: 'High-strength superalloy for turbine disks.',
            laborMultiplier: 4.5,
            usedIn: ['turbine_disks', 'engine_parts', 'high_temp']
        },
        {
            id: 'rene_88',
            name: 'René 88',
            formula: 'Ni + 0.16Cr + 0.13Co + 0.04W + 0.03Mo + 0.03Ti + 0.02Al → Advanced',
            ingredients: { Nickel: 55, Chromium: 16, Cobalt: 13, Tungsten: 4, Molybdenum: 3, Titanium: 3, Aluminum: 2 },
            field: 'metallurgy',
            category: 'Nickel Superalloys',
            tier: 5,
            skillGain: 70,
            target: 1000,
            icon: '✨',
            unlocksAt: 10000,
            value: 5000,
            description: 'Advanced superalloy for turbine blades.',
            laborMultiplier: 5.0,
            usedIn: ['turbine_blades', 'high_temp', 'aerospace']
        }
    ],
    
    'Cobalt Superalloys': [
        {
            id: 'stellite_6',
            name: 'Stellite 6',
            formula: 'Co + 0.28Cr + 0.04W + 0.01C → Co₆₇Cr₂₈W₄C',
            ingredients: { Cobalt: 67, Chromium: 28, Tungsten: 4, Carbon: 1 },
            field: 'metallurgy',
            category: 'Cobalt Superalloys',
            tier: 5,
            skillGain: 40,
            target: 1000,
            icon: '⚙️',
            unlocksAt: 8000,
            value: 2800,
            description: 'Wear-resistant alloy for valve seats and bearings.',
            laborMultiplier: 3.2,
            usedIn: ['valves', 'bearings', 'wear_pads']
        },
        {
            id: 'stellite_21',
            name: 'Stellite 21',
            formula: 'Co + 0.27Cr + 0.05Mo + 0.02Ni → Co₆₆Cr₂₇Mo₅Ni₂',
            ingredients: { Cobalt: 66, Chromium: 27, Molybdenum: 5, Nickel: 2 },
            field: 'metallurgy',
            category: 'Cobalt Superalloys',
            tier: 5,
            skillGain: 45,
            target: 1000,
            icon: '🔧',
            unlocksAt: 8500,
            value: 3000,
            description: 'Tough cobalt alloy for high-temperature service.',
            laborMultiplier: 3.5,
            usedIn: ['turbine', 'valves', 'pumps']
        },
        {
            id: 'haynes_25',
            name: 'Haynes 25',
            formula: 'Co + 0.20Cr + 0.15W + 0.10Ni → Co₅₅Cr₂₀W₁₅Ni₁₀',
            ingredients: { Cobalt: 55, Chromium: 20, Tungsten: 15, Nickel: 10 },
            field: 'metallurgy',
            category: 'Cobalt Superalloys',
            tier: 5,
            skillGain: 50,
            target: 1000,
            icon: '🔥',
            unlocksAt: 9000,
            value: 3500,
            description: 'High-temperature alloy for combustion chambers.',
            laborMultiplier: 4.0,
            usedIn: ['combustion_liners', 'afterburners', 'heat_shields']
        }
    ],
    
    // ============================================================================
    // TIER 6: POWDER METALLURGY (15 recipes)
    // ============================================================================
    
    'Powder Production': [
        {
            id: 'atomize_metal',
            name: 'Metal Atomization',
            formula: 'Molten Metal + High Pressure Gas → Powder',
            ingredients: { MoltenSteel: 10, Argon: 5 },
            field: 'metallurgy',
            category: 'Powder Production',
            tier: 6,
            skillGain: 25,
            target: 2000,
            icon: '💨',
            unlocksAt: 15000,
            value: 400,
            description: 'Create fine metal powder for powder metallurgy.',
            laborMultiplier: 2.2,
            usedIn: ['metal_powder', 'additive_manufacturing']
        },
        {
            id: 'mechanical_alloying',
            name: 'Mechanical Alloying',
            formula: 'Metal Powders + Ball Milling → Alloy Powder',
            ingredients: { IronPowder: 5, NickelPowder: 5, ChromiumPowder: 2 },
            field: 'metallurgy',
            category: 'Powder Production',
            tier: 6,
            skillGain: 35,
            target: 2000,
            icon: '⚙️',
            unlocksAt: 16000,
            value: 600,
            description: 'Create alloy powders through high-energy milling.',
            laborMultiplier: 2.5,
            usedIn: ['ods_alloys', 'specialty_powders']
        },
        {
            id: 'reduce_oxide',
            name: 'Hydrogen Reduction',
            formula: 'Metal Oxide + H₂ → Metal Powder + H₂O',
            ingredients: { IronOxide: 10, Hydrogen: 10 },
            field: 'metallurgy',
            category: 'Powder Production',
            tier: 6,
            skillGain: 20,
            target: 2000,
            icon: '💧',
            unlocksAt: 15500,
            value: 350,
            description: 'Reduce metal oxides to pure metal powder.',
            laborMultiplier: 2.0,
            usedIn: ['iron_powder', 'copper_powder']
        }
    ],
    
    'Sintering': [
        {
            id: 'sinter_iron',
            name: 'Sinter Iron Powder',
            formula: 'Iron Powder + Heat → Solid',
            ingredients: { IronPowder: 10 },
            field: 'metallurgy',
            category: 'Sintering',
            tier: 6,
            skillGain: 20,
            target: 2000,
            icon: '🔥',
            unlocksAt: 17000,
            value: 200,
            description: 'Sinter iron powder into solid form.',
            laborMultiplier: 1.8,
            usedIn: ['sintered_parts', 'gears']
        },
        {
            id: 'sinter_bronze',
            name: 'Sinter Bronze',
            formula: 'Bronze Powder + Heat → Porous Bronze',
            ingredients: { BronzePowder: 10 },
            field: 'metallurgy',
            category: 'Sintering',
            tier: 6,
            skillGain: 22,
            target: 2000,
            icon: '🔧',
            unlocksAt: 17500,
            value: 250,
            description: 'Sinter bronze for self-lubricating bearings.',
            laborMultiplier: 1.9,
            usedIn: ['bearings', 'filters', 'bushings']
        },
        {
            id: 'sinter_tungsten',
            name: 'Sinter Tungsten',
            formula: 'Tungsten Powder + Heat → Solid',
            ingredients: { TungstenPowder: 10 },
            field: 'metallurgy',
            category: 'Sintering',
            tier: 6,
            skillGain: 40,
            target: 2000,
            icon: '⚡',
            unlocksAt: 20000,
            value: 800,
            description: 'Sinter tungsten for high-density applications.',
            laborMultiplier: 3.0,
            usedIn: ['counterweights', 'radiation_shielding']
        }
    ],
    
    'Hot Isostatic Pressing': [
        {
            id: 'hip_steel',
            name: 'HIP Steel',
            formula: 'Steel Powder + Heat + Pressure → Dense',
            ingredients: { SteelPowder: 10 },
            field: 'metallurgy',
            category: 'Hot Isostatic Pressing',
            tier: 6,
            skillGain: 45,
            target: 2000,
            icon: '⚡',
            unlocksAt: 22000,
            value: 1000,
            description: 'Hot isostatic pressing for fully dense steel.',
            laborMultiplier: 3.5,
            usedIn: ['critical_parts', 'aerospace']
        },
        {
            id: 'hip_titanium',
            name: 'HIP Titanium',
            formula: 'Titanium Powder + Heat + Pressure → Dense',
            ingredients: { TitaniumPowder: 10 },
            field: 'metallurgy',
            category: 'Hot Isostatic Pressing',
            tier: 6,
            skillGain: 60,
            target: 2000,
            icon: '✈️',
            unlocksAt: 25000,
            value: 2000,
            description: 'HIP titanium for aerospace components.',
            laborMultiplier: 4.5,
            usedIn: ['aircraft_parts', 'medical_implants']
        },
        {
            id: 'hip_superalloy',
            name: 'HIP Superalloy',
            formula: 'Superalloy Powder + Heat + Pressure → Dense',
            ingredients: { SuperalloyPowder: 10 },
            field: 'metallurgy',
            category: 'Hot Isostatic Pressing',
            tier: 6,
            skillGain: 80,
            target: 2000,
            icon: '🚀',
            unlocksAt: 30000,
            value: 4000,
            description: 'HIP superalloy for turbine disks.',
            laborMultiplier: 5.0,
            usedIn: ['turbine_disks', 'engine_parts']
        }
    ],
    
    // ============================================================================
    // TIER 7: ADVANCED ALLOYS (20 recipes)
    // ============================================================================
    
    'Titanium Alloys': [
        {
            id: 'ti64',
            name: 'Ti-6Al-4V (Grade 5)',
            formula: 'Ti + 0.06Al + 0.04V → Ti₉₀Al₆V₄',
            ingredients: { Titanium: 90, Aluminum: 6, Vanadium: 4 },
            field: 'metallurgy',
            category: 'Titanium Alloys',
            tier: 7,
            skillGain: 60,
            target: 5000,
            icon: '✈️',
            unlocksAt: 40000,
            value: 5000,
            description: 'Workhorse titanium alloy for aerospace.',
            laborMultiplier: 4.0,
            usedIn: ['aircraft', 'medical', 'automotive']
        },
        {
            id: 'ti6242',
            name: 'Ti-6Al-2Sn-4Zr-2Mo',
            formula: 'Ti + 0.06Al + 0.02Sn + 0.04Zr + 0.02Mo → Complex',
            ingredients: { Titanium: 86, Aluminum: 6, Tin: 2, Zirconium: 4, Molybdenum: 2 },
            field: 'metallurgy',
            category: 'Titanium Alloys',
            tier: 7,
            skillGain: 75,
            target: 5000,
            icon: '🔥',
            unlocksAt: 45000,
            value: 7000,
            description: 'High-temperature titanium alloy for jet engines.',
            laborMultiplier: 5.0,
            usedIn: ['compressor_disks', 'engine_parts']
        },
        {
            id: 'ti5553',
            name: 'Ti-5Al-5Mo-5V-3Cr',
            formula: 'Ti + 0.05Al + 0.05Mo + 0.05V + 0.03Cr → Complex',
            ingredients: { Titanium: 82, Aluminum: 5, Molybdenum: 5, Vanadium: 5, Chromium: 3 },
            field: 'metallurgy',
            category: 'Titanium Alloys',
            tier: 7,
            skillGain: 80,
            target: 5000,
            icon: '🔧',
            unlocksAt: 50000,
            value: 8000,
            description: 'High-strength titanium for landing gear.',
            laborMultiplier: 5.5,
            usedIn: ['landing_gear', 'structural']
        }
    ],
    
    'Magnesium Alloys': [
        {
            id: 'az31',
            name: 'AZ31 Magnesium',
            formula: 'Mg + 0.03Al + 0.01Zn → Mg₉₆Al₃Zn₁',
            ingredients: { Magnesium: 96, Aluminum: 3, Zinc: 1 },
            field: 'metallurgy',
            category: 'Magnesium Alloys',
            tier: 7,
            skillGain: 30,
            target: 5000,
            icon: '✨',
            unlocksAt: 42000,
            value: 2000,
            description: 'Lightweight magnesium for portable devices.',
            laborMultiplier: 2.5,
            usedIn: ['laptops', 'power_tools', 'auto_parts']
        },
        {
            id: 'zk60',
            name: 'ZK60 Magnesium',
            formula: 'Mg + 0.06Zn + 0.005Zr → Mg₉₃Zn₆Zr₁',
            ingredients: { Magnesium: 93, Zinc: 6, Zirconium: 1 },
            field: 'metallurgy',
            category: 'Magnesium Alloys',
            tier: 7,
            skillGain: 40,
            target: 5000,
            icon: '⚡',
            unlocksAt: 45000,
            value: 2500,
            description: 'High-strength magnesium alloy.',
            laborMultiplier: 3.0,
            usedIn: ['aerospace', 'racing', 'sports']
        }
    ],
    
    'Zirconium Alloys': [
        {
            id: 'zircaloy_2',
            name: 'Zircaloy-2',
            formula: 'Zr + 0.015Sn + 0.015Fe + 0.01Cr → Zr₉₆Sn₁₅Fe₁₅Cr₁',
            ingredients: { Zirconium: 96, Tin: 1.5, Iron: 1.5, Chromium: 1 },
            field: 'metallurgy',
            category: 'Zirconium Alloys',
            tier: 7,
            skillGain: 80,
            target: 5000,
            icon: '☢️',
            unlocksAt: 60000,
            value: 10000,
            description: 'Nuclear-grade zirconium for fuel cladding.',
            laborMultiplier: 6.0,
            usedIn: ['nuclear_fuel', 'reactors']
        },
        {
            id: 'zircaloy_4',
            name: 'Zircaloy-4',
            formula: 'Zr + 0.015Sn + 0.02Fe + 0.01Cr → Zr₉₅Sn₁₅Fe₂Cr₁',
            ingredients: { Zirconium: 95, Tin: 1.5, Iron: 2, Chromium: 1 },
            field: 'metallurgy',
            category: 'Zirconium Alloys',
            tier: 7,
            skillGain: 85,
            target: 5000,
            icon: '☢️',
            unlocksAt: 65000,
            value: 11000,
            description: 'Improved zirconium alloy for nuclear reactors.',
            laborMultiplier: 6.5,
            usedIn: ['nuclear', 'chemical']
        }
    ]
};

// ============================================================================
// EXPORT ALL METALLURGY RECIPES
// ============================================================================

export default METALLURGY_RECIPES;
