// js/crafting/fields/polymers.js
// Polymers & Plastics Recipes - 60+ recipes for synthetic materials
// Tier 1-7: From Basic Monomers to Advanced Engineering Plastics

export const POLYMERS_RECIPES = {
    
    // ============================================================================
    // TIER 1: BASIC MONOMERS (10 recipes)
    // ============================================================================
    
    'Monomers': [
        {
            id: 'ethylene',
            name: 'Ethylene',
            formula: 'C₂H₄ → CH₂=CH₂',
            ingredients: { Carbon: 2, Hydrogen: 4 },
            field: 'polymers',
            category: 'Monomers',
            tier: 1,
            skillGain: 3,
            target: 100,
            icon: '🧪',
            unlocksAt: 0,
            value: 30,
            description: 'The most produced organic compound. Used to make polyethylene.',
            laborMultiplier: 1.2,
            usedIn: ['polyethylene', 'ethylene_glycol', 'styrene']
        },
        {
            id: 'propylene',
            name: 'Propylene',
            formula: 'C₃H₆ → CH₃-CH=CH₂',
            ingredients: { Carbon: 3, Hydrogen: 6 },
            field: 'polymers',
            category: 'Monomers',
            tier: 1,
            skillGain: 4,
            target: 100,
            icon: '🧪',
            unlocksAt: 50,
            value: 35,
            description: 'Used to make polypropylene and other plastics.',
            laborMultiplier: 1.2,
            usedIn: ['polypropylene', 'acrylonitrile', 'propylene_oxide']
        },
        {
            id: 'styrene',
            name: 'Styrene',
            formula: 'C₆H₅-CH=CH₂',
            ingredients: { Carbon: 8, Hydrogen: 8 },
            field: 'polymers',
            category: 'Monomers',
            tier: 1,
            skillGain: 6,
            target: 100,
            icon: '🧪',
            unlocksAt: 100,
            value: 50,
            description: 'Monomer for polystyrene and many copolymers.',
            laborMultiplier: 1.3,
            usedIn: ['polystyrene', 'abs', 'rubber']
        },
        {
            id: 'vinyl_chloride',
            name: 'Vinyl Chloride',
            formula: 'CH₂=CH-Cl',
            ingredients: { Carbon: 2, Hydrogen: 3, Chlorine: 1 },
            field: 'polymers',
            category: 'Monomers',
            tier: 1,
            skillGain: 5,
            target: 100,
            icon: '🧪',
            unlocksAt: 150,
            value: 45,
            description: 'Monomer for PVC. Toxic but essential.',
            laborMultiplier: 1.3,
            usedIn: ['pvc', 'plastics', 'pipes']
        },
        {
            id: 'acrylonitrile',
            name: 'Acrylonitrile',
            formula: 'CH₂=CH-C≡N',
            ingredients: { Carbon: 3, Hydrogen: 3, Nitrogen: 1 },
            field: 'polymers',
            category: 'Monomers',
            tier: 1,
            skillGain: 6,
            target: 100,
            icon: '🧪',
            unlocksAt: 200,
            value: 60,
            description: 'Used in acrylic fibers and ABS plastic.',
            laborMultiplier: 1.4,
            usedIn: ['acrylic', 'abs', 'fibers']
        },
        {
            id: 'methyl_methacrylate',
            name: 'Methyl Methacrylate',
            formula: 'CH₂=C(CH₃)COOCH₃',
            ingredients: { Carbon: 5, Hydrogen: 8, Oxygen: 2 },
            field: 'polymers',
            category: 'Monomers',
            tier: 1,
            skillGain: 8,
            target: 100,
            icon: '🔍',
            unlocksAt: 250,
            value: 80,
            description: 'Monomer for Plexiglas (PMMA).',
            laborMultiplier: 1.5,
            usedIn: ['plexiglas', 'acrylic', 'optical']
        },
        {
            id: 'caprolactam',
            name: 'Caprolactam',
            formula: 'C₆H₁₁NO',
            ingredients: { Carbon: 6, Hydrogen: 11, Nitrogen: 1, Oxygen: 1 },
            field: 'polymers',
            category: 'Monomers',
            tier: 1,
            skillGain: 9,
            target: 100,
            icon: '🧵',
            unlocksAt: 300,
            value: 90,
            description: 'Monomer for Nylon 6.',
            laborMultiplier: 1.6,
            usedIn: ['nylon', 'fibers', 'plastics']
        },
        {
            id: 'formaldehyde',
            name: 'Formaldehyde',
            formula: 'CH₂O',
            ingredients: { Carbon: 1, Hydrogen: 2, Oxygen: 1 },
            field: 'polymers',
            category: 'Monomers',
            tier: 1,
            skillGain: 3,
            target: 100,
            icon: '🧪',
            unlocksAt: 75,
            value: 25,
            description: 'Basic building block for thermoset resins.',
            laborMultiplier: 1.2,
            usedIn: ['bakelite', 'melamine', 'urea_formaldehyde']
        },
        {
            id: 'bisphenol_a',
            name: 'Bisphenol A',
            formula: '(CH₃)₂C(C₆H₄OH)₂',
            ingredients: { Carbon: 15, Hydrogen: 16, Oxygen: 2 },
            field: 'polymers',
            category: 'Monomers',
            tier: 1,
            skillGain: 10,
            target: 100,
            icon: '🧪',
            unlocksAt: 350,
            value: 100,
            description: 'Key monomer for polycarbonate and epoxy resins.',
            laborMultiplier: 1.7,
            usedIn: ['polycarbonate', 'epoxy', 'thermal_paper']
        },
        {
            id: 'terephthalic_acid',
            name: 'Terephthalic Acid',
            formula: 'C₆H₄(COOH)₂',
            ingredients: { Carbon: 8, Hydrogen: 6, Oxygen: 4 },
            field: 'polymers',
            category: 'Monomers',
            tier: 1,
            skillGain: 8,
            target: 100,
            icon: '🧪',
            unlocksAt: 400,
            value: 85,
            description: 'Monomer for PET polyester.',
            laborMultiplier: 1.5,
            usedIn: ['pet', 'polyester', 'fibers']
        }
    ],
    
    // ============================================================================
    // TIER 2: BASIC POLYMERS (15 recipes)
    // ============================================================================
    
    'Polyolefins': [
        {
            id: 'ldpe',
            name: 'Low-Density Polyethylene (LDPE)',
            formula: 'n(C₂H₄) → (C₂H₄)n',
            ingredients: { Ethylene: 20 },
            field: 'polymers',
            category: 'Polyolefins',
            tier: 2,
            skillGain: 8,
            target: 200,
            icon: '🛍️',
            unlocksAt: 500,
            value: 60,
            description: 'Flexible, transparent plastic for bags and films.',
            laborMultiplier: 1.4,
            usedIn: ['plastic_bags', 'squeeze_bottles', 'film']
        },
        {
            id: 'hdpe',
            name: 'High-Density Polyethylene (HDPE)',
            formula: 'n(C₂H₄) → Linear (C₂H₄)n',
            ingredients: { Ethylene: 20 },
            field: 'polymers',
            category: 'Polyolefins',
            tier: 2,
            skillGain: 9,
            target: 200,
            icon: '🥛',
            unlocksAt: 550,
            value: 70,
            description: 'Strong, rigid plastic for bottles and containers.',
            laborMultiplier: 1.5,
            usedIn: ['milk_jugs', 'detergent_bottles', 'pipes']
        },
        {
            id: 'polypropylene',
            name: 'Polypropylene (PP)',
            formula: 'n(C₃H₆) → (C₃H₆)n',
            ingredients: { Propylene: 20 },
            field: 'polymers',
            category: 'Polyolefins',
            tier: 2,
            skillGain: 10,
            target: 200,
            icon: '🧴',
            unlocksAt: 600,
            value: 80,
            description: 'Durable plastic for packaging, textiles, and automotive parts.',
            laborMultiplier: 1.5,
            usedIn: ['containers', 'textiles', 'automotive']
        },
        {
            id: 'polybutylene',
            name: 'Polybutylene',
            formula: 'n(C₄H₈) → (C₄H₈)n',
            ingredients: { Butene: 20 },
            field: 'polymers',
            category: 'Polyolefins',
            tier: 2,
            skillGain: 12,
            target: 200,
            icon: '🔧',
            unlocksAt: 700,
            value: 100,
            description: 'Flexible polymer for piping and packaging.',
            laborMultiplier: 1.6,
            usedIn: ['pipes', 'seals', 'packaging']
        }
    ],
    
    'Styrenics': [
        {
            id: 'gpps',
            name: 'General Purpose Polystyrene (GPPS)',
            formula: 'n(C₈H₈) → (C₈H₈)n',
            ingredients: { Styrene: 20 },
            field: 'polymers',
            category: 'Styrenics',
            tier: 2,
            skillGain: 10,
            target: 200,
            icon: '📦',
            unlocksAt: 800,
            value: 70,
            description: 'Clear, rigid plastic for containers and disposables.',
            laborMultiplier: 1.5,
            usedIn: ['cd_cases', 'cutlery', 'containers']
        },
        {
            id: 'hips',
            name: 'High-Impact Polystyrene (HIPS)',
            formula: 'PS + Polybutadiene → Impact Modified',
            ingredients: { Polystyrene: 15, Polybutadiene: 5 },
            field: 'polymers',
            category: 'Styrenics',
            tier: 2,
            skillGain: 12,
            target: 200,
            icon: '🛡️',
            unlocksAt: 850,
            value: 90,
            description: 'Toughened polystyrene for durable products.',
            laborMultiplier: 1.6,
            usedIn: ['appliances', 'toys', 'electronics']
        },
        {
            id: 'eps',
            name: 'Expandable Polystyrene (EPS)',
            formula: 'PS + Blowing Agent → Foam',
            ingredients: { Polystyrene: 15, Pentane: 3 },
            field: 'polymers',
            category: 'Styrenics',
            tier: 2,
            skillGain: 11,
            target: 200,
            icon: '📦',
            unlocksAt: 900,
            value: 65,
            description: 'Foamed polystyrene for insulation and packaging.',
            laborMultiplier: 1.5,
            usedIn: ['styrofoam', 'insulation', 'packaging']
        },
        {
            id: 'san',
            name: 'Styrene-Acrylonitrile (SAN)',
            formula: 'Styrene + Acrylonitrile → Copolymer',
            ingredients: { Styrene: 15, Acrylonitrile: 5 },
            field: 'polymers',
            category: 'Styrenics',
            tier: 2,
            skillGain: 14,
            target: 200,
            icon: '✨',
            unlocksAt: 950,
            value: 110,
            description: 'Clear, chemical-resistant plastic.',
            laborMultiplier: 1.7,
            usedIn: ['cosmetic_containers', 'batteries', 'appliances']
        }
    ],
    
    'Vinyl Polymers': [
        {
            id: 'pvc',
            name: 'Polyvinyl Chloride (PVC)',
            formula: 'n(C₂H₃Cl) → (C₂H₃Cl)n',
            ingredients: { VinylChloride: 20 },
            field: 'polymers',
            category: 'Vinyl Polymers',
            tier: 2,
            skillGain: 10,
            target: 200,
            icon: '🔧',
            unlocksAt: 1000,
            value: 75,
            description: 'Versatile plastic for pipes, fittings, and insulation.',
            laborMultiplier: 1.5,
            usedIn: ['pipes', 'fittings', 'insulation']
        },
        {
            id: 'cpvc',
            name: 'Chlorinated PVC (CPVC)',
            formula: 'PVC + Cl₂ → Chlorinated',
            ingredients: { PVC: 15, Chlorine: 5 },
            field: 'polymers',
            category: 'Vinyl Polymers',
            tier: 2,
            skillGain: 13,
            target: 200,
            icon: '🔥',
            unlocksAt: 1100,
            value: 100,
            description: 'Heat-resistant PVC for hot water pipes.',
            laborMultiplier: 1.6,
            usedIn: ['hot_water_pipes', 'industrial_plumbing']
        },
        {
            id: 'pvac',
            name: 'Polyvinyl Acetate (PVAc)',
            formula: 'n(C₄H₆O₂) → (C₄H₆O₂)n',
            ingredients: { VinylAcetate: 20 },
            field: 'polymers',
            category: 'Vinyl Polymers',
            tier: 2,
            skillGain: 9,
            target: 200,
            icon: '🧴',
            unlocksAt: 1050,
            value: 60,
            description: 'Adhesive polymer for wood glue and paints.',
            laborMultiplier: 1.4,
            usedIn: ['wood_glue', 'paints', 'paper_coatings']
        }
    ],
    
    'Acrylics': [
        {
            id: 'pmma',
            name: 'Polymethyl Methacrylate (PMMA)',
            formula: 'n(C₅H₈O₂) → (C₅H₈O₂)n',
            ingredients: { MethylMethacrylate: 20 },
            field: 'polymers',
            category: 'Acrylics',
            tier: 2,
            skillGain: 12,
            target: 200,
            icon: '🔍',
            unlocksAt: 1200,
            value: 120,
            description: 'Plexiglas. A transparent alternative to glass.',
            laborMultiplier: 1.6,
            usedIn: ['windows', 'signs', 'optical']
        },
        {
            id: 'polyacrylate',
            name: 'Polyacrylate',
            formula: 'n(C₃H₄O₂) → (C₃H₄O₂)n',
            ingredients: { AcrylicAcid: 20 },
            field: 'polymers',
            category: 'Acrylics',
            tier: 2,
            skillGain: 10,
            target: 200,
            icon: '💧',
            unlocksAt: 1250,
            value: 90,
            description: 'Super-absorbent polymer for diapers and gels.',
            laborMultiplier: 1.5,
            usedIn: ['diapers', 'hydrogels', 'thickeners']
        }
    ],
    
    // ============================================================================
    // TIER 3: ENGINEERING PLASTICS (12 recipes)
    // ============================================================================
    
    'Polyamides': [
        {
            id: 'nylon_6',
            name: 'Nylon 6',
            formula: 'Caprolactam → Polymerization',
            ingredients: { Caprolactam: 20 },
            field: 'polymers',
            category: 'Polyamides',
            tier: 3,
            skillGain: 15,
            target: 300,
            icon: '🧵',
            unlocksAt: 2000,
            value: 150,
            description: 'Strong, durable polyamide for fibers and engineering.',
            laborMultiplier: 1.8,
            usedIn: ['textiles', 'carpet', 'gears']
        },
        {
            id: 'nylon_66',
            name: 'Nylon 6,6',
            formula: 'Hexamethylenediamine + Adipic Acid → Polycondensation',
            ingredients: { Hexamethylenediamine: 10, AdipicAcid: 10 },
            field: 'polymers',
            category: 'Polyamides',
            tier: 3,
            skillGain: 18,
            target: 300,
            icon: '🧵',
            unlocksAt: 2200,
            value: 180,
            description: 'High-strength nylon for engineering applications.',
            laborMultiplier: 2.0,
            usedIn: ['textiles', 'engineering', 'automotive']
        },
        {
            id: 'nylon_12',
            name: 'Nylon 12',
            formula: 'Laurolactam → Polymerization',
            ingredients: { Laurolactam: 20 },
            field: 'polymers',
            category: 'Polyamides',
            tier: 3,
            skillGain: 20,
            target: 300,
            icon: '🔧',
            unlocksAt: 2500,
            value: 220,
            description: 'Flexible nylon with low moisture absorption.',
            laborMultiplier: 2.1,
            usedIn: ['tubing', 'coatings', 'automotive']
        }
    ],
    
    'Polyesters': [
        {
            id: 'pet',
            name: 'Polyethylene Terephthalate (PET)',
            formula: 'Ethylene Glycol + Terephthalic Acid → Polyester',
            ingredients: { EthyleneGlycol: 10, TerephthalicAcid: 10 },
            field: 'polymers',
            category: 'Polyesters',
            tier: 3,
            skillGain: 16,
            target: 300,
            icon: '🥤',
            unlocksAt: 2800,
            value: 160,
            description: 'Common polyester for bottles and fibers.',
            laborMultiplier: 1.9,
            usedIn: ['bottles', 'fibers', 'packaging']
        },
        {
            id: 'pbt',
            name: 'Polybutylene Terephthalate (PBT)',
            formula: 'Butanediol + Terephthalic Acid → Polyester',
            ingredients: { Butanediol: 10, TerephthalicAcid: 10 },
            field: 'polymers',
            category: 'Polyesters',
            tier: 3,
            skillGain: 18,
            target: 300,
            icon: '🔌',
            unlocksAt: 3000,
            value: 200,
            description: 'Engineering polyester for electrical components.',
            laborMultiplier: 2.0,
            usedIn: ['connectors', 'automotive', 'electronics']
        },
        {
            id: 'pct',
            name: 'Polycyclohexylene Terephthalate (PCT)',
            formula: 'High-Temperature Polyester',
            ingredients: { Cyclohexanedimethanol: 10, TerephthalicAcid: 10 },
            field: 'polymers',
            category: 'Polyesters',
            tier: 3,
            skillGain: 22,
            target: 300,
            icon: '🔥',
            unlocksAt: 3300,
            value: 280,
            description: 'High-temperature polyester for LED components.',
            laborMultiplier: 2.3,
            usedIn: ['LEDs', 'automotive', 'electronics']
        }
    ],
    
    'Polycarbonates': [
        {
            id: 'polycarbonate',
            name: 'Polycarbonate (PC)',
            formula: 'Bisphenol A + Phosgene → Polycarbonate',
            ingredients: { BisphenolA: 15, Phosgene: 5 },
            field: 'polymers',
            category: 'Polycarbonates',
            tier: 3,
            skillGain: 20,
            target: 300,
            icon: '🛡️',
            unlocksAt: 3500,
            value: 250,
            description: 'Impact-resistant transparent plastic.',
            laborMultiplier: 2.2,
            usedIn: ['bulletproof_glass', 'cds', 'eyewear']
        },
        {
            id: 'pc_abs',
            name: 'PC/ABS Blend',
            formula: 'Polycarbonate + ABS → Blend',
            ingredients: { Polycarbonate: 10, ABS: 10 },
            field: 'polymers',
            category: 'Polycarbonates',
            tier: 3,
            skillGain: 22,
            target: 300,
            icon: '⚙️',
            unlocksAt: 3800,
            value: 280,
            description: 'Tough, heat-resistant blend for automotive interiors.',
            laborMultiplier: 2.3,
            usedIn: ['dashboards', 'electronics', 'appliances']
        }
    ],
    
    // ============================================================================
    // TIER 4: THERMOSETS (10 recipes)
    // ============================================================================
    
    'Epoxy Resins': [
        {
            id: 'epoxy_resin',
            name: 'Epoxy Resin',
            formula: 'Bisphenol A + Epichlorohydrin → Epoxy',
            ingredients: { BisphenolA: 12, Epichlorohydrin: 8 },
            field: 'polymers',
            category: 'Epoxy Resins',
            tier: 4,
            skillGain: 20,
            target: 400,
            icon: '🧴',
            unlocksAt: 4000,
            value: 220,
            description: 'High-performance thermoset for adhesives and composites.',
            laborMultiplier: 2.1,
            usedIn: ['adhesives', 'coatings', 'composites']
        },
        {
            id: 'epoxy_hardener',
            name: 'Epoxy Hardener (Amine)',
            formula: 'Amine + Additives → Curing Agent',
            ingredients: { Amine: 15, Catalyst: 2 },
            field: 'polymers',
            category: 'Epoxy Resins',
            tier: 4,
            skillGain: 15,
            target: 400,
            icon: '⚗️',
            unlocksAt: 4200,
            value: 150,
            description: 'Curing agent for epoxy resins.',
            laborMultiplier: 1.8,
            usedIn: ['epoxy_curing', 'adhesives']
        },
        {
            id: 'epoxy_compound',
            name: 'Epoxy Casting Compound',
            formula: 'Epoxy Resin + Hardener → Cured Epoxy',
            ingredients: { EpoxyResin: 10, EpoxyHardener: 5 },
            field: 'polymers',
            category: 'Epoxy Resins',
            tier: 4,
            skillGain: 25,
            target: 400,
            icon: '💎',
            unlocksAt: 4500,
            value: 300,
            description: 'Castable epoxy for prototyping and encapsulation.',
            laborMultiplier: 2.3,
            usedIn: ['prototypes', 'encapsulation', 'art']
        }
    ],
    
    'Phenolic Resins': [
        {
            id: 'bakelite',
            name: 'Bakelite (Phenolic)',
            formula: 'Phenol + Formaldehyde → Thermoset',
            ingredients: { Phenol: 12, Formaldehyde: 8 },
            field: 'polymers',
            category: 'Phenolic Resins',
            tier: 4,
            skillGain: 18,
            target: 400,
            icon: '📻',
            unlocksAt: 4800,
            value: 180,
            description: 'First synthetic plastic. Heat-resistant and insulating.',
            laborMultiplier: 2.0,
            usedIn: ['electrical', 'pot_handles', 'vintage']
        },
        {
            id: 'phenolic_molding',
            name: 'Phenolic Molding Compound',
            formula: 'Phenolic Resin + Fillers → Molding Powder',
            ingredients: { Bakelite: 10, WoodFlour: 5 },
            field: 'polymers',
            category: 'Phenolic Resins',
            tier: 4,
            skillGain: 20,
            target: 400,
            icon: '🔌',
            unlocksAt: 5000,
            value: 200,
            description: 'Compression molding compound for electrical parts.',
            laborMultiplier: 2.1,
            usedIn: ['outlets', 'switches', 'automotive']
        }
    ],
    
    'Polyurethanes': [
        {
            id: 'polyurethane_foam',
            name: 'Polyurethane Foam',
            formula: 'Polyol + Isocyanate + Blowing Agent → Foam',
            ingredients: { Polyol: 10, Isocyanate: 10, BlowingAgent: 2 },
            field: 'polymers',
            category: 'Polyurethanes',
            tier: 4,
            skillGain: 22,
            target: 400,
            icon: '🛏️',
            unlocksAt: 5500,
            value: 150,
            description: 'Flexible or rigid foam for insulation and cushioning.',
            laborMultiplier: 2.2,
            usedIn: ['mattresses', 'insulation', 'seating']
        },
        {
            id: 'polyurethane_elastomer',
            name: 'Polyurethane Elastomer',
            formula: 'Polyol + Isocyanate → Thermoplastic',
            ingredients: { Polyol: 12, Isocyanate: 8 },
            field: 'polymers',
            category: 'Polyurethanes',
            tier: 4,
            skillGain: 24,
            target: 400,
            icon: '⚽',
            unlocksAt: 5800,
            value: 250,
            description: 'Flexible, abrasion-resistant polymer for wheels and seals.',
            laborMultiplier: 2.3,
            usedIn: ['wheels', 'seals', 'hoses']
        },
        {
            id: 'spandex',
            name: 'Spandex (Elastane)',
            formula: 'Polyurethane + Segments → Elastic Fiber',
            ingredients: { PolyurethaneElastomer: 15, SpinningProcess: 1 },
            field: 'polymers',
            category: 'Polyurethanes',
            tier: 4,
            skillGain: 28,
            target: 400,
            icon: '🧘',
            unlocksAt: 6000,
            value: 350,
            description: 'Elastic fiber for stretch clothing.',
            laborMultiplier: 2.5,
            usedIn: ['activewear', 'swimwear', 'underwear']
        }
    ],
    
    // ============================================================================
    // TIER 5: HIGH-PERFORMANCE POLYMERS (8 recipes)
    // ============================================================================
    
    'Fluoropolymers': [
        {
            id: 'ptfe',
            name: 'Polytetrafluoroethylene (PTFE)',
            formula: 'n(C₂F₄) → (C₂F₄)n',
            ingredients: { Tetrafluoroethylene: 20 },
            field: 'polymers',
            category: 'Fluoropolymers',
            tier: 5,
            skillGain: 30,
            target: 500,
            icon: '🍳',
            unlocksAt: 8000,
            value: 500,
            description: 'Teflon. Non-stick, heat-resistant, and chemically inert.',
            laborMultiplier: 2.8,
            usedIn: ['nonstick', 'seals', 'electrical']
        },
        {
            id: 'fep',
            name: 'Fluorinated Ethylene Propylene (FEP)',
            formula: 'TFE + HFP → Melt-Processable Fluoropolymer',
            ingredients: { Tetrafluoroethylene: 15, Hexafluoropropylene: 5 },
            field: 'polymers',
            category: 'Fluoropolymers',
            tier: 5,
            skillGain: 32,
            target: 500,
            icon: '🔌',
            unlocksAt: 8500,
            value: 550,
            description: 'Melt-processable fluoropolymer for wire insulation.',
            laborMultiplier: 3.0,
            usedIn: ['wire_insulation', 'tubing', 'coatings']
        },
        {
            id: 'pvdf',
            name: 'Polyvinylidene Fluoride (PVDF)',
            formula: 'n(C₂H₂F₂) → (C₂H₂F₂)n',
            ingredients: { VinylideneFluoride: 20 },
            field: 'polymers',
            category: 'Fluoropolymers',
            tier: 5,
            skillGain: 28,
            target: 500,
            icon: '🎨',
            unlocksAt: 8200,
            value: 480,
            description: 'Strong fluoropolymer for chemical processing and coatings.',
            laborMultiplier: 2.7,
            usedIn: ['pipe_liners', 'valves', 'cable_coating']
        }
    ],
    
    'High-Temperature Polymers': [
        {
            id: 'peek',
            name: 'Polyether Ether Ketone (PEEK)',
            formula: 'Difluorobenzophenone + Hydroquinone → Polymer',
            ingredients: { Difluorobenzophenone: 10, Hydroquinone: 10 },
            field: 'polymers',
            category: 'High-Temperature Polymers',
            tier: 5,
            skillGain: 40,
            target: 500,
            icon: '🚀',
            unlocksAt: 10000,
            value: 800,
            description: 'Ultra-high performance polymer for aerospace and medical.',
            laborMultiplier: 3.5,
            usedIn: ['aerospace', 'medical_implants', 'oil_gas']
        },
        {
            id: 'polyimide',
            name: 'Polyimide (PI)',
            formula: 'PMDA + ODA → Polycondensation',
            ingredients: { PyromelliticDianhydride: 10, DiaminodiphenylEther: 10 },
            field: 'polymers',
            category: 'High-Temperature Polymers',
            tier: 5,
            skillGain: 38,
            target: 500,
            icon: '📟',
            unlocksAt: 9500,
            value: 750,
            description: 'Exceptional thermal stability for electronics.',
            laborMultiplier: 3.3,
            usedIn: ['flexible_circuits', 'insulation', 'space']
        },
        {
            id: 'pei',
            name: 'Polyetherimide (PEI)',
            formula: 'Bisphenol A + Nitro-substituted → Amorphous',
            ingredients: { BisphenolA: 12, NitroCompound: 8 },
            field: 'polymers',
            category: 'High-Temperature Polymers',
            tier: 5,
            skillGain: 35,
            target: 500,
            icon: '💡',
            unlocksAt: 9200,
            value: 680,
            description: 'Transparent high-temperature plastic for electronics.',
            laborMultiplier: 3.2,
            usedIn: ['electronics', 'medical', 'lighting']
        }
    ],
    
    'Liquid Crystal Polymers': [
        {
            id: 'lcp',
            name: 'Liquid Crystal Polymer (LCP)',
            formula: 'Aromatic Polyester → Ordered Structure',
            ingredients: { HydroxybenzoicAcid: 15, HydroxynaphthoicAcid: 5 },
            field: 'polymers',
            category: 'Liquid Crystal Polymers',
            tier: 5,
            skillGain: 42,
            target: 500,
            icon: '💎',
            unlocksAt: 11000,
            value: 900,
            description: 'Self-reinforcing polymer with exceptional strength.',
            laborMultiplier: 3.8,
            usedIn: ['connectors', 'electronics', 'fiber_optics']
        }
    ],
    
    // ============================================================================
    // TIER 6: SPECIALTY POLYMERS (8 recipes)
    // ============================================================================
    
    'Conductive Polymers': [
        {
            id: 'pani',
            name: 'Polyaniline (PANI)',
            formula: 'Aniline + Oxidant → Conductive Polymer',
            ingredients: { Aniline: 15, AmmoniumPersulfate: 5 },
            field: 'polymers',
            category: 'Conductive Polymers',
            tier: 6,
            skillGain: 35,
            target: 600,
            icon: '⚡',
            unlocksAt: 15000,
            value: 600,
            description: 'Conductive polymer for antistatic coatings.',
            laborMultiplier: 3.0,
            usedIn: ['antistatic', 'sensors', 'corrosion_protection']
        },
        {
            id: 'pedot',
            name: 'PEDOT:PSS',
            formula: 'EDOT + Polystyrene Sulfonate → Conductive Blend',
            ingredients: { EDOT: 10, PSS: 10 },
            field: 'polymers',
            category: 'Conductive Polymers',
            tier: 6,
            skillGain: 40,
            target: 600,
            icon: '🖥️',
            unlocksAt: 16000,
            value: 750,
            description: 'Transparent conductive polymer for displays.',
            laborMultiplier: 3.3,
            usedIn: ['touch_screens', 'oled', 'solar_cells']
        },
        {
            id: 'polypyrrole',
            name: 'Polypyrrole',
            formula: 'Pyrrole + Oxidation → Conductive',
            ingredients: { Pyrrole: 15, IronChloride: 5 },
            field: 'polymers',
            category: 'Conductive Polymers',
            tier: 6,
            skillGain: 38,
            target: 600,
            icon: '🧪',
            unlocksAt: 15500,
            value: 650,
            description: 'Conductive polymer for biosensors and actuators.',
            laborMultiplier: 3.1,
            usedIn: ['biosensors', 'actuators', 'electrodes']
        }
    ],
    
    'Biodegradable Polymers': [
        {
            id: 'pla',
            name: 'Polylactic Acid (PLA)',
            formula: 'Lactic Acid → Polycondensation',
            ingredients: { LacticAcid: 20 },
            field: 'polymers',
            category: 'Biodegradable Polymers',
            tier: 6,
            skillGain: 25,
            target: 600,
            icon: '🌱',
            unlocksAt: 14000,
            value: 300,
            description: 'Biodegradable plastic from renewable resources.',
            laborMultiplier: 2.5,
            usedIn: ['3d_printing', 'packaging', 'compostable']
        },
        {
            id: 'pga',
            name: 'Polyglycolic Acid (PGA)',
            formula: 'Glycolic Acid → Polymer',
            ingredients: { GlycolicAcid: 20 },
            field: 'polymers',
            category: 'Biodegradable Polymers',
            tier: 6,
            skillGain: 28,
            target: 600,
            icon: '🩹',
            unlocksAt: 14500,
            value: 400,
            description: 'Biodegradable polymer for medical sutures.',
            laborMultiplier: 2.7,
            usedIn: ['surgical_sutures', 'implants', 'packaging']
        },
        {
            id: 'phb',
            name: 'Polyhydroxybutyrate (PHB)',
            formula: 'Bacterial Fermentation → Polyester',
            ingredients: { Sugar: 30, Bacteria: 1 },
            field: 'polymers',
            category: 'Biodegradable Polymers',
            tier: 6,
            skillGain: 32,
            target: 600,
            icon: '🧪',
            unlocksAt: 15000,
            value: 450,
            description: 'Bioplastic produced by bacteria.',
            laborMultiplier: 2.8,
            usedIn: ['packaging', 'medical', 'agriculture']
        }
    ],
    
    // ============================================================================
    // TIER 7: ADVANCED POLYMER COMPOSITES (7 recipes)
    // ============================================================================
    
    'Fiber-Reinforced': [
        {
            id: 'carbon_fiber_composite',
            name: 'Carbon Fiber Reinforced Polymer (CFRP)',
            formula: 'Carbon Fibers + Epoxy → Composite',
            ingredients: { CarbonFiber: 10, EpoxyResin: 10 },
            field: 'polymers',
            category: 'Fiber-Reinforced',
            tier: 7,
            skillGain: 50,
            target: 800,
            icon: '🏎️',
            unlocksAt: 20000,
            value: 1200,
            description: 'Ultra-light, ultra-strong composite for high-performance applications.',
            laborMultiplier: 4.0,
            usedIn: ['aerospace', 'automotive', 'sports_equipment']
        },
        {
            id: 'glass_fiber_composite',
            name: 'Glass Fiber Reinforced Polymer (GFRP)',
            formula: 'Glass Fibers + Polyester → Fiberglass',
            ingredients: { GlassFiber: 15, PolyesterResin: 10 },
            field: 'polymers',
            category: 'Fiber-Reinforced',
            tier: 7,
            skillGain: 40,
            target: 800,
            icon: '🛶',
            unlocksAt: 18000,
            value: 500,
            description: 'Fiberglass for boats, automotive, and construction.',
            laborMultiplier: 3.2,
            usedIn: ['boats', 'auto_bodies', 'tanks']
        },
        {
            id: 'kevlar_composite',
            name: 'Kevlar Reinforced Polymer',
            formula: 'Aramid Fibers + Epoxy → Ballistic Composite',
            ingredients: { KevlarFiber: 12, EpoxyResin: 8 },
            field: 'polymers',
            category: 'Fiber-Reinforced',
            tier: 7,
            skillGain: 55,
            target: 800,
            icon: '🛡️',
            unlocksAt: 22000,
            value: 1500,
            description: 'Bulletproof composite for armor and protection.',
            laborMultiplier: 4.5,
            usedIn: ['body_armor', 'helmets', 'vehicle_armor']
        }
    ],
    
    'Self-Healing Polymers': [
        {
            id: 'self_healing_elastomer',
            name: 'Self-Healing Elastomer',
            formula: 'Polymer + Dynamic Bonds → Self-Healing',
            ingredients: { PolyurethaneElastomer: 15, ReversibleCrosslinker: 5 },
            field: 'polymers',
            category: 'Self-Healing Polymers',
            tier: 7,
            skillGain: 60,
            target: 800,
            icon: '🔄',
            unlocksAt: 25000,
            value: 2000,
            description: 'Rubber that repairs itself when cut.',
            laborMultiplier: 5.0,
            usedIn: ['tires', 'seals', 'protective_coatings']
        },
        {
            id: 'microcapsule_self_healing',
            name: 'Microcapsule Self-Healing Polymer',
            formula: 'Polymer + Healing Agent Microcapsules → Autonomous Repair',
            ingredients: { EpoxyResin: 15, Microcapsules: 5, Catalyst: 2 },
            field: 'polymers',
            category: 'Self-Healing Polymers',
            tier: 7,
            skillGain: 70,
            target: 800,
            icon: '💊',
            unlocksAt: 28000,
            value: 3000,
            description: 'Advanced material that heals cracks automatically.',
            laborMultiplier: 6.0,
            usedIn: ['aerospace', 'infrastructure', 'electronics']
        }
    ],
    
    'Shape Memory Polymers': [
        {
            id: 'shape_memory_pu',
            name: 'Shape Memory Polyurethane',
            formula: 'Polyurethane + Crosslinking → Programmable Shape',
            ingredients: { PolyurethaneElastomer: 18, Crosslinker: 2 },
            field: 'polymers',
            category: 'Shape Memory Polymers',
            tier: 7,
            skillGain: 65,
            target: 800,
            icon: '🔄',
            unlocksAt: 26000,
            value: 2500,
            description: 'Polymer that remembers and returns to its original shape.',
            laborMultiplier: 5.5,
            usedIn: ['actuators', 'medical_devices', 'deployable_structures']
        }
    ],
    
    // ============================================================================
    // ADDITIONAL: POLYMER ADDITIVES (Helper recipes)
    // ============================================================================
    
    'Additives': [
        {
            id: 'plasticizer',
            name: 'Plasticizer (Phthalate)',
            formula: 'Phthalic Anhydride + Alcohol → Ester',
            ingredients: { PhthalicAnhydride: 10, Alcohol: 8 },
            field: 'polymers',
            category: 'Additives',
            tier: 2,
            skillGain: 8,
            target: 200,
            icon: '💧',
            unlocksAt: 900,
            value: 40,
            description: 'Adds flexibility to rigid polymers like PVC.',
            laborMultiplier: 1.4,
            usedIn: ['flexible_pvc', 'vinyl', 'hoses']
        },
        {
            id: 'uv_stabilizer',
            name: 'UV Stabilizer',
            formula: 'HALS + UV Absorber → Protection',
            ingredients: { HinderedAmine: 8, Benzotriazole: 4 },
            field: 'polymers',
            category: 'Additives',
            tier: 3,
            skillGain: 12,
            target: 300,
            icon: '☀️',
            unlocksAt: 2000,
            value: 80,
            description: 'Protects polymers from UV degradation.',
            laborMultiplier: 1.6,
            usedIn: ['outdoor_plastics', 'automotive', 'packaging']
        },
        {
            id: 'flame_retardant',
            name: 'Flame Retardant',
            formula: 'Brominated Compound + Antimony Trioxide → Fire Resistance',
            ingredients: { BrominatedCompound: 10, AntimonyTrioxide: 3 },
            field: 'polymers',
            category: 'Additives',
            tier: 4,
            skillGain: 18,
            target: 400,
            icon: '🔥',
            unlocksAt: 3500,
            value: 150,
            description: 'Adds fire resistance to polymers.',
            laborMultiplier: 1.9,
            usedIn: ['electronics', 'construction', 'transportation']
        },
        {
            id: 'antioxidant',
            name: 'Antioxidant',
            formula: 'Phenolic Compound + Phosphite → Stabilization',
            ingredients: { PhenolicAntioxidant: 8, Phosphite: 4 },
            field: 'polymers',
            category: 'Additives',
            tier: 3,
            skillGain: 10,
            target: 300,
            icon: '🧪',
            unlocksAt: 1800,
            value: 60,
            description: 'Prevents polymer degradation during processing.',
            laborMultiplier: 1.5,
            usedIn: ['all_plastics', 'processing']
        },
        {
            id: 'colorant_masterbatch',
            name: 'Colorant Masterbatch',
            formula: 'Pigment + Carrier Resin → Concentrate',
            ingredients: { Pigment: 10, Polyethylene: 10 },
            field: 'polymers',
            category: 'Additives',
            tier: 2,
            skillGain: 7,
            target: 200,
            icon: '🎨',
            unlocksAt: 1000,
            value: 50,
            description: 'Concentrated color for plastics.',
            laborMultiplier: 1.3,
            usedIn: ['colored_plastics', 'packaging', 'products']
        }
    ]
};

// ============================================================================
// EXPORT ALL POLYMERS RECIPES
// ============================================================================

export default POLYMERS_RECIPES;
